### ISSUE TITLE
Add in support for registering data via redirect

### ISSUE THREAD

**Issue by amoeba** [whole-tale/dashboard#105]
(We had a small group on our weekly dev call today so whether we do this is still up for discussion but I thought I'd get an issue in here as the feature may not be very controversial)

To support registering data into WholeTale from outside the Dashboard (i.e., from search.dataone.org), it would be great if the Dashboard could handle a web redirect and register the provided dataset into the Dashboard for the user to work with. This would support the proposal [here](https://github.com/whole-tale/wt-design-docs/tree/master/mockups/dataone-integration).

The basic idea is that the user would be able to follow a flow like this:

1. Be on https://search.dataone.org/#view/doi:10.18739/A2JB90
2. Click a button on that page (e.g., "Add to WholeTale")
3. Be redirected to the Dashboard (conditionally through the Globus Auth process to log in) to a URL such as https://dashboard.wholetale.org/catalog/add/doi:10.18739/A2JB90
4. See the newly-added dataset in their My Data

From which point they could Compose a new Tale

**Comment by ThomasThelen** [comment]
This is implemented in in commit bc0cbc9.
