### ISSUE TITLE
Expand "Configuration" tab in "Create Image"

### ISSUE THREAD

**Issue by Xarthisius** [whole-tale/dashboard#111]
Currently 'Create Image' utilizes only 3 out of 7 config variables ('user', 'command', 'targetMount'). It would be really nice to add at least 'port' and 'urlPath'.

**Comment by swyngaard** [comment]
Resolved in [1e91c4e](https://github.com/whole-tale/dashboard/commit/1e91c4ea132b5517542b36eb04c77e63d98407ad).

Please test and let me know if we need to add any additional configuration settings.

**Comment by Xarthisius** [comment]
This is perfect! thanks!
