### ISSUE TITLE
Download context-menu item not working

### ISSUE THREAD

**Issue by amoeba** [whole-tale/dashboard#113]
Steps to reproduce:

- Go to dev dashboard
- Go to Data tab
- Right click on a file I see
- Click Download
- See no change in the UI, no download starts

<img width="536" alt="screen shot 2018-02-21 at 3 47 16 pm" src="https://user-images.githubusercontent.com/563/36504441-8435cec6-171e-11e8-8ac5-bf3dc380fb5c.png">

Expected behavior: Either download starts immediately or a something in the UI should at least change

**Comment by ThomasThelen** [comment]
Tested in Build: v0.7rc2-0-gf3777e6
Status: Unable to reproduce
