### ISSUE TITLE
Advanced/simplified menu toggle

### ISSUE THREAD

**Issue by craig-willis** [whole-tale/dashboard#118]
Allow users to switch between current and simplified (quickstart) UI

Completion criteria:
* Implement UI changes
* Define test case
* Update documentation
* Pull request
* Deploy to dev

**Comment by bodom0015** [comment]
@craig-willis is this still a thing? I'm thinking this is stale enough to close..

**Comment by craig-willis** [comment]
Indeed. This was based on input from a 2018 AHM meeting after Binder launched.  We've gone through several UI refactors since then.
