### ISSUE TITLE
File Browser Neglects Nested Folders for Parent Size Calculation

### ISSUE THREAD

**Issue by ThomasThelen** [whole-tale/dashboard#123]
It appears that the file browser widget is calculating the size only from files one level lower in the structure, and ignoring nested folders.

As an example, consider the second element in the the file listing below.

<img width="1078" alt="screen shot 2018-03-19 at 1 30 29 pm" src="https://user-images.githubusercontent.com/9289652/37620555-cc6dd85e-2b79-11e8-97fb-f6a4d66ae249.png">

Although the package is listed as having a size of 0, we can see that there are additional folders with data. The same behavior is exhibited here, where the folders  with size 0 have nested folders with data inside.

<img width="1094" alt="screen shot 2018-03-19 at 1 30 59 pm" src="https://user-images.githubusercontent.com/9289652/37620571-d8e234fe-2b79-11e8-8250-3e1604420dd3.png">

To reproduce:
Import `https://search.dataone.org/#view/urn:uuid:6f5533ab-6508-4ac7-82a3-1df88ed4580e`
Navigate to "My Data"
Explore the folders & note the reported sizes.

**Comment by ThomasThelen** [comment]
I was mucking around in 
`http://girder.readthedocs.io/en/latest/_modules/girder/models/folder.html`
and saw the function, `getSizeRecursive` that looks handy here,

**Comment by bodom0015** [comment]
This seems to still be present, but it appears to have nothing to do with the dashboard.

@Xarthisius can this be closed, or does it need to be tracked on the Girder side?
