### ISSUE TITLE
Catching Iframe Error Upon a Refused to Display Error - Difficulty 9

### ISSUE THREAD

**Issue by abrinckm** [whole-tale/dashboard#128]
Files: components/dashboard/run/left-panel 
 
Iframes are implemented but we need a reliable way to catch load errors e.g. Something like this is shown in the Chrome console:

Refused to display 'http://tmp-fgwgrqygdpm0.dev.wholetale.org/auth-sign-in' in a frame 

But they are hard to catch in Javascript.  I tried the following

Getting var frame = document.getElementById('frontendDisplay');   and then trying the onload function.  This returns without error whether the iFrame was loaded or whether there is a refused to show message
Trying to see what is loaded:  Doing any iframe.contentWindow.document or similar results in a “same origin” issue.
I tried onload and onerror also in JS but onload is called regardless and onerror is never called.

Once this is figured out, then we need to display a message on the left when an iFrame cannot be loaded.

**Comment by craig-willis** [comment]
This was solved by adding the explicit `iframe` boolean. Auto-detection is not necessary.
