### ISSUE TITLE
Back button support

### ISSUE THREAD

**Issue by matthewturk** [whole-tale/dashboard#13]
When I use the dashboard, often hitting the back button in the browser (or reloading the URL) breaks things.  Is it possible to get back/forward support?

**Comment by ian-taylor** [comment]
I think this is a server issue - we need mod rewrite or equivalent
installed so the URL rewriting works ok. This works ok for me locally on
apache. I'll investigate a little

**Comment by Xarthisius** [comment]
@ian-taylor can you share you apache2.conf ?

**Comment by ian-taylor** [comment]
This is the httpd.conf that we use on another server that is hosting an Ember app. Relative urls and using the back on the browser works fine on this server. We also have a .htaccess file - attached too. I can include this .htaccess file for wholetale but I thought that Nginx was being used so wasn’t sure what the configuration for that should be. 



Ian Taylor,
Research Professor, University of Notre Dame
Reader, Cardiff University
ian.j.taylor@gmail.com

**Comment by Xarthisius** [comment]
Should be fixed by following changes to nginx-proxy config:

```
$ cat /srv/nginx/vhost.d/dashboard-dev.wholetale.org
## Start of configuration add by letsencrypt container
location /.well-known/acme-challenge/ {
    allow all;
    root /usr/share/nginx/html;
    try_files $uri =404;
    break;
}

location @rewrite_proxy {
	rewrite ^/(.*)$ /?$1 break;
	proxy_pass http://dashboard-dev.wholetale.org;
	proxy_set_header Host $host;
	proxy_set_header X-Forwarded-For $remote_addr;
}

$ cat /srv/nginx/vhost.d/dashboard-dev.wholetale.org_location
proxy_set_header Host $host;
proxy_set_header X-Forwarded-For $remote_addr;
proxy_intercept_errors on;
recursive_error_pages on;
error_page 404 = @rewrite_proxy;
```
@MatthewTurk can you verify?

**Comment by MatthewTurk** [comment]
Works for reloading the page, but when I click back after in-page nav, it goes back to previous page.

**Comment by Xarthisius** [comment]
I guess that requires catching 'back' event within file browser? @abrinckm any suggestions?

**Comment by ian-taylor** [comment]
Matt, when you say in page nav, are you talking about the file browser specifically? or can you give a few examples?

**Comment by MatthewTurk** [comment]
Yup, I did specifically mean that.

**Comment by ian-taylor** [comment]
ok, rewriting all of that atm so I'll look.

**Comment by ThomasThelen** [comment]
A note about the current back functionality. It's possible to log out, press the back button a couple of times, and see a mangled view of what the last user had open. The image below was captured after I was viewing the catalog, logged out, and then pressed back. When attempting to launch the last person's tale, you are prompted to log in, so it looks like you only have read access. I'm not sure if this is an issue, but it might be worth noting (if this is the wrong place let me know!).

![screen shot 2018-02-27 at 5 28 10 pm](https://user-images.githubusercontent.com/9289652/36764954-e7ba295a-1be3-11e8-8abe-a2b796018e5c.png)

**Comment by Xarthisius** [comment]
I believe this was fixed long time ago. (re-open if I'm wrong)
