### ISSUE TITLE
New File Manager Update and UI - Difficulty 10

### ISSUE THREAD

**Issue by abrinckm** [whole-tale/dashboard#130]
Files: components/dashboard/manage/left-panel 

For the left tab, we need a new UI that Kristina designed implemented, shown above. There are several aspects to this:
Left browse buttons need implementing and pointing to the right directories.
The file manager Implementation and editing capabilities need restyling for the new space and checking for functionality to see if everything works.

**Comment by cyberdante** [comment]
@abrinckm from feedback we got from beta users, the NEW FOLDER button should be removed in the new UI.
