### ISSUE TITLE
Dropzone Already Attached Error

### ISSUE THREAD

**Issue by ThomasThelen** [whole-tale/dashboard#134]
When registering multiple data sets, the second attempt will not be possible due to an exception coming from the dropzone.
`Uncaught Error: Dropzone already attached.`

My workaround that usually works is to close the browser and re-open it.

To Reproduce:
   1. Open the data registration dialog
   2. Register a dataset
   3. Open the dialog again
   4. Attempt to select the dataset from the dropdown
   5. Notice that you can't select the dropdown (see console for errors)
   6. Enter random text into the URI field, see the error for each character entered

**Comment by abrinckm** [comment]
@ThomasThelen Can you try and repoduce this error, we may have fixed this with recent work.

**Comment by ThomasThelen** [comment]
@abrinckm I tried to reproduce this on Chrome and Firefox but was unable to; It looks fixed to me.
