### ISSUE TITLE
Adding the Footer

### ISSUE THREAD

**Issue by abrinckm** [whole-tale/dashboard#135]

**Comment by abrinckm** [comment]
File: templates/application.hbs

The footer needs adding back in once the above issue has been solved. Add:

{{partial "common/footer"}}

To the enmd of the {{#if newUIMode}}

Section, and then deal with the styling and potential overlapping.

**Comment by cyberdante** [comment]
This issue has been completed. Can be verified on *newui* branch; commit [a5705a2](https://github.com/whole-tale/dashboard/commit/a5705a229af8cda2fc0b0b82d1d136f868b4ba76) includes the changes to the proper footer styling with respect to the panels above.
