### ISSUE TITLE
 Styling of Left and right panels

### ISSUE THREAD

**Issue by abrinckm** [whole-tale/dashboard#137]

**Comment by abrinckm** [comment]
Files: 
components/dashboard/unified-view and 
styles/wholetale-dashboard.scss, in:

.ui.grid > .row.panel.container {
}


The left panel should use some fixed window size so the iFrame is consistent. This kind of works right now using the   height: 85vh; but needs some experimenting.

Also, the right side panels should occupy the right amount of space:
When there is one panel, it should be the same size as the left panel
When there are two panels on top of each other, each should occupy half the space and the result should be same size as the left panel

**Comment by cyberdante** [comment]
This issue is now done. Can be verified after commit [f80ae27](https://github.com/whole-tale/dashboard/commit/f80ae2774e53fad656c633cb0436f171381e1ac0) on branch *newui*
