### ISSUE TITLE
Selecting an instance on Right

### ISSUE THREAD

**Issue by abrinckm** [whole-tale/dashboard#139]

**Comment by abrinckm** [comment]
Files: components/dashboard/browse/right-panel 

When selecting an instance, the route should be transitioned to Run with the selected instance being shown on the left portion of the view.

**Comment by ian-taylor** [comment]
@swyngaard Is this resolved?

**Comment by swyngaard** [comment]
Yes, I believe it is working  as expected. You're welcome to close this issue.
