### ISSUE TITLE
 Instantiating Tales 

### ISSUE THREAD

**Issue by abrinckm** [whole-tale/dashboard#140]

**Comment by abrinckm** [comment]
We need to change the way Tales are instantiated so that when the launch button is pressed, the spinner appears on the right instances column not in the main column, so that several tales can be started at once.

**Comment by swyngaard** [comment]
Resolved in [c37751e](https://github.com/whole-tale/dashboard/commit/c37751e3efd336a8d6ca415046fbce6f37d144c7)

**Comment by craig-willis** [comment]
Whooo!
