### ISSUE TITLE
Sticky Menu on the Dashboard (allows left menu to be always shown)

### ISSUE THREAD

**Issue by Xarthisius** [whole-tale/dashboard#15]

**Comment by ian-taylor** [comment]
I've been thinking about this and I think I can do this using the ember display property to switch between different menus, rather than making the sliding menu stick - which is a lot harder to do.

**Comment by MatthewTurk** [comment]
From an experience perspective, if I wasn't told that the menu slid out, I wouldn't know.  I think this should just be always, always out; the times I think people will want to collapse it are vanishingly small.

**Comment by ian-taylor** [comment]
I really don’t think we can make that call until we get feedback from WT users. So, I think having the option for either would be a better starting point.

**Comment by MatthewTurk** [comment]
There are no clues right now as to whether it even opens or not; every time I click, it re-collapses.  I believe that going into UX studies, which we have not yet timelined, will be very useful all around; at the present time, though, I think we should default to what the people who we know are using it (i.e., the developer team and the PI team) prefer, and then allow for modification later.  If we hold off on all UX decisions until proper studies can be conducted, we won't be able to make any decisions.

I'll bring this up at the PI meeting tomorrow and get back to you with feedback for how to proceed in the interim before the UX studies can be conducted.  My personal feeling is that at the present time, defaulting to open is the right move; however, I don't think we can find a lot of disagreement that having it default to closed without at least a hint (hamburger icon, for instance) that it can be expanded is not going to work as a medium-term solution.  I'll present it (with as little personal bias as possible :smile:) tomorrow and update this ticket.

**Comment by ian-taylor** [comment]
Currently the hamburger icon is the WT icon but we can easily add a hamburger icon and move the whole tale icon across to accommodate, or put the hamburger on the top right.    

Having both options I think could work ok i.e. a fixed menu or a pop out one. This could be user configurable.

Some potential disadvantages IMHO however for a fixed left menu are the following:

- they take a fixed space from your workspace and make it cluttered - for applications that require frequent menu changes this maybe ok but for wholetale, I don’t think this is the case. Links within pages should prompt the user in their workflow so I don't see the need for a constant navigation widget  
- they do not work on smaller screens, so if we want to support mobile phones or even tablets then we’ll have to implement something else later on.

**Comment by MatthewTurk** [comment]
I will also present to the PI team your concerns that this would negatively impact mobile, but from my perspective mobile is not our priority at this time.  I respect and understand our desire to keep the compatibility there, but for this particular issue I believe that implementing something else later on is highly preferred to the current navigation status.

I will update this ticket tomorrow after discussion, but my feeling has not changed, and I believe we either need to re-evaluate the navigation strategy to avoid this issue entirely, or make the existing approach have the navigation bar always open.

**Comment by ian-taylor** [comment]
Mobile was a side aspect, the primary was the clutter. It seems drastic to completely re-evaluate this when a simple hamburger icon could solve this issue. https://hangouts.google.com/ uses a similar approach.  If not, then check out https://semantic-ui.com/ to see if any of those menus would work. 

We need to change the menu anyway because the navigation menus need updating, based on discussions in Austin. Maybe we can start a ticket discussing what those new menu options should be e.g. upload should probably be changed to something else e.g. Files, Finder or something.

**Comment by MatthewTurk** [comment]
So, we discussed this, and the PI team expressed that we should have the menu out by default.  It can remain collapsible, but by default, discoverability is quite low (and overloaded with the common usage of "Click on logo to go to the home page") and we need to upfront this, more akin to gmail/gdrive than hangouts.  I would be happy to discuss this on a call, but I think we need to move forward with the default-to-open (and possibly a LocalStorage preference or something for if it should be collapsed).

If you'd like suggestions on the menu specifics, I can go through and try to pick something out, but I think you should also feel broad latitude within those specifications to pick one out.

The PI team also expressed that we shouldn't prioritize mobile for 18 month deliverables, and just try to keep it somewhat responsive.  (I know you also noted this earlier.)

**Comment by ian-taylor** [comment]
ok, that was what we had planned for anyway so all good, except that it will be out by default. I'll have a go at it this week.

**Comment by Xarthisius** [comment]
Fixed in 61a046a
