### ISSUE TITLE
View tale problems on new UI

### ISSUE THREAD

**Issue by craig-willis** [whole-tale/dashboard#150]
Seeing some strange behaviors with the new UI  tale view on dev under both Chrome and Safari. It looks like it might be related to the footer placement.  At first, I couldn't see some of the functions (edit tale, view properties).  At some point I was able to resize/scroll and I now see them, but the footer is moving. The margins are also odd now that there isn't a left sidebar (as in the old UI).

<img width="1159" alt="screen shot 2018-06-25 at 3 20 19 pm" src="https://user-images.githubusercontent.com/4334350/41873677-5074d176-788b-11e8-9bba-6b5b9999fc4e.png">

**Comment by cyberdante** [comment]
@craig-willis we hadn't touched this page as it was not part of the UI overhaul. I believe this to be fixed now. Could you please check again?

**Comment by craig-willis** [comment]
This looks good to me. I did notice that it appears as though I can edit someone else's tale (title and description boxes are enabled), but update results in 403.  I've confirmed that this is the same behavior as on production. This seems undesirable -- should I open a separate ticket?

**Comment by cyberdante** [comment]
No need, really. This issue can help us track those small glitches as we find them, given the broad title it has. I will take a look at this behavior next. Thanks again @craig-willis!

**Comment by cyberdante** [comment]
I would not show the `Edit Tale` accordion panel if the current user is not an admin or the owner of the current tale.
