### ISSUE TITLE
Back Button Goes Back Too Far

### ISSUE THREAD

**Issue by ThomasThelen** [whole-tale/dashboard#151]
After navigating through a few pages and clicking the `Back` button (The in the dashboard) it will bring you back too far.

1. Navigate to https://newdashboard.dev.wholetale.org/browse
2. Hover the `Example Tale using R` Tale and click `View`
3. Scroll to the bottom of `View` and click `View Tale Properties`
4. Scroll down and click the eye button next to `Folder`
5. Click `Back` in the folder info page

Note that it brings you back to `Browse` instead of the tale view

**Comment by cyberdante** [comment]
@ThomasThelen I believe this was fixed while restyling the tale's folder view. Could you please verify?

**Comment by ThomasThelen** [comment]
Confirmed that it has been fixed
Tested in: `Build: 56d4af1`

**Comment by cyberdante** [comment]
Thank you, @ThomasThelen!
