### ISSUE TITLE
Info Icon is Rendered as a Solid Fill

### ISSUE THREAD

**Issue by ThomasThelen** [whole-tale/dashboard#152]
Info icon popup in the data registration modal is filled with blue.

1. Go to **https://newdashboard.dev.wholetale.org/manage/**
2. Click the `Plus` icon on the lefthand side next to `Linked from external sources`.
3. Hover over the icon next to `Reference URL`

Seen on Chrome Version 67.0.3396.87 (Official Build) (64-bit)
<img width="862" alt="screen shot 2018-06-25 at 3 26 30 pm" src="https://user-images.githubusercontent.com/9289652/41878951-36c9735c-788c-11e8-8f30-3fadbcab93ce.png">

**Comment by cyberdante** [comment]
Fixed tooltip:
![Screen Shot 2018-07-02 at 4.42.48 PM.png](https://images.zenhubusercontent.com/5af1b4ba4b5806bc2bd249f9/d71523a3-9958-42dc-90b9-8ab2b5eeef19)

Fix should be verifiable after next deployment.

**Comment by Xarthisius** [comment]
It looks like this here:
![tooltip](https://user-images.githubusercontent.com/352673/42186386-1c89c25e-7e12-11e8-8dcc-57128d4a7476.png)

```

Data exported | 2018-07-02T21:08:32.751Z
Chrome version | Chrome/69.0.3472.3
Operating system | Linux 4.12.0-gentoo
Software rendering list URL | https://chromium.googlesource.com/chromium/src/+/b978b9c8052fb79ad76080d8b6e7539e4e797693/gpu/config/software_rendering_list.json
Driver bug list URL | https://chromium.googlesource.com/chromium/src/+/b978b9c8052fb79ad76080d8b6e7539e4e797693/gpu/config/gpu_driver_bug_list.json
ANGLE commit id | f5fd5c6c6a21
2D graphics backend | Skia/69 ebf160f308b698c075c9c1cf8d65d40cb2486238-
Command Line | /usr/bin/google-chrome-unstable --extra-plugin-dir=/usr/lib64/nsbrowser/plugins --extra-plugin-dir=/usr/lib64/nsbrowser/plugins --extra-plugin-dir=/usr/lib64/nsbrowser/plugins --extra-plugin-dir=/usr/lib64/nsbrowser/plugins --force-device-scale-factor=2 --flag-switches-begin --flag-switches-end
```

**Comment by Xarthisius** [comment]
Works for me now, thank you! (Fixed in https://github.com/whole-tale/dashboard/commit/4a0e53cb11309cc214b357bf9cb83d86526ea3a1)
