### ISSUE TITLE
Unable to Rename Files

### ISSUE THREAD

**Issue by ThomasThelen** [whole-tale/dashboard#153]
In the file browser I'm not able to rename any files. The `Rename` button remains greyed out and I'm not sure why.

To reproduce, use the file browser to find a file and try to rename it.

<img width="1102" alt="screen shot 2018-06-25 at 4 57 50 pm" src="https://user-images.githubusercontent.com/9289652/41881561-fa20b610-7898-11e8-958a-bb8dc6499408.png">

**Comment by abrinckm** [comment]
Try without any special characters. If it works without special characters, then the issue should be reported to Mihael. 

I had this same problem using spaces in the name, but I can successfully rename the file without any spaces.

**Comment by abrinckm** [comment]
This is the same issue as commented in #191. It was resolved, confirmed by @craig-willis
