### ISSUE TITLE
Unable to Create a Folder in a Folder

### ISSUE THREAD

**Issue by ThomasThelen** [whole-tale/dashboard#156]
In the data management area, specifically the file browser I'm not able to nest folders. For example, I can create a folder, `myFolder`. I can navigate inside the folder and click the `Create Folder` icon-but it brings me back out to the root directory and will place the folder there.

To Reproduce:
1. Navigate to https://newdashboard.dev.wholetale.org/manage
2. Move your mouse over the blue `plus` icon.
3. Click `Create Folder`
4. Name it and click `New`
5. Navigate inside the folder
6. Repeat 2-4
7. Note that you're now in the outermost directory, and your new folder is also there (and not inside the one created in step 4.

**Comment by abrinckm** [comment]
I reproduce this easily. Clicking anywhere in the navigator (like create folder) will navigate to that directory. So clicking new folder does two things, navigates to home, and opens modal. So that is likely the issue. 

Narrowing the click region for navigating might resolve this issue.

**Comment by abrinckm** [comment]
prevent default event when clicking on create folder for anything else that shouldn't cause the browser to navigate

**Comment by abrinckm** [comment]
Resolved in [9826038](https://github.com/whole-tale/dashboard/commit/9826038ee6865aed3ce39a4d2727f6ff92710965)

@ThomasThelen Can you check to see if this is okay now?

**Comment by ThomasThelen** [comment]
This looks good to me in 1053701
