### ISSUE TITLE
Restyle the view tale page

### ISSUE THREAD

**Issue by abrinckm** [whole-tale/dashboard#160]

**Comment by cyberdante** [comment]
This is already styled to match the rest of the look and feel of the redesigned dashboard but a link here takes the user to a `Folder view` which needs styling as well. Creating new issue to take care of that separately.

<img width="946" alt="screen shot 2018-06-26 at 2 56 24 pm" src="https://user-images.githubusercontent.com/20361247/41933232-4768cf12-7951-11e8-90bc-84c17f506004.png">
