### ISSUE TITLE
Restyle the tales' folder view page

### ISSUE THREAD

**Issue by cyberdante** [whole-tale/dashboard#162]
Name should also change as it will allow for the user to see the tale's involatile data

**Comment by Xarthisius** [comment]
Change the name, but you can keep the behavior. 'folderId' now points to a folder that contains a copy of all data provided by `involatileData` array.

**Comment by cyberdante** [comment]
Working now:

<img width="1888" alt="screen shot 2018-06-27 at 10 58 44 am" src="https://user-images.githubusercontent.com/20361247/41982312-1ade9a5a-79f9-11e8-9e35-7bfb41b48d5d.png">
