### ISSUE TITLE
Files Still Showing / Not Deleting After Deletion

### ISSUE THREAD

**Issue by ThomasThelen** [whole-tale/dashboard#164]
I noticed this as I was cleaning up my `Data` folder in the `Manage` section.

1. I probably deleted ~40 - 50 datasets that I had registered.
2. After deleting them all, I navigated away from the page to `Compose`. I tried to navigate back to 
    `Manage`, but each left click was unresponsive. 
3. Next I clicked `Run`, and was able to click `Manage` once on the `Run` page. 
4. Once on the `Manage` page, I clicked the `Data` folder section

I saw that there were maybe ~15 or so datasets were showing in the browser. I went ahead and deleted them all, navigated to the `Run` page, and had trouble clicking `Manage` again. I right clicked and opened in a new tab. 

I noticed again that there were a few sets remaining, so I deleted them. I refreshed the page, and one item remained (see image).

Every time I delete this file it comes back after I refresh the page. I noticed that there was also a file with the same name in the `Home` directory so I deleted it. Navigating back to the `Data` folder, the file remained. I tried deleting it again but was unable to do so.

I searched girder for an item with the filename, `d2c.jpg`, but no results were found.

Edit: I was registering data ~17 minutes after creating this issue and I see that `d2c.jpg` is now gone.
Edit 2: The file came back, and I also saw a hand full of the datasets that I had deleted earlier. Refreshing the page got rid of all except `d2c.jpg`.

![screen shot 2018-06-26 at 1 26 41 pm](https://user-images.githubusercontent.com/9289652/41937330-e1380066-7944-11e8-86ef-c6673e30c4d9.png)

**Comment by ThomasThelen** [comment]
I tested this in the latest (ceac1b7) and was unable to reproduce it.

**Comment by craig-willis** [comment]
@ThomasThelen  Can this be closed?

**Comment by ThomasThelen** [comment]
Unable to reproduce. Closing.
