### ISSUE TITLE
Tale Browser Has Incorrect State after Tale Deletion in Search

### ISSUE THREAD

**Issue by ThomasThelen** [whole-tale/dashboard#168]
I was deleting a set of tales whose name shared a common word. To do this I went to the `Browse` tab and searched the tales for the common word. After deleting one, the widget reset the search, but left the search term in the search field (see image).

Build: `56d4af1`

To Reproduce:
   1. Create two tales, name them 'mytale1' and 'mytale2`
   2. Go to `Browse`
   3. Search for `myTale`
   4. Delete one of them
   5. Note the behavior described above.

<img width="1680" alt="screen shot 2018-06-27 at 2 40 00 pm" src="https://user-images.githubusercontent.com/9289652/42001262-558aecac-7a18-11e8-8bbd-ee657c85acb4.png">

**Comment by ThomasThelen** [comment]
Update: Still present in build `5eae564` (Nov-15-2018)

**Comment by Xarthisius** [comment]
Fixed by https://github.com/whole-tale/dashboard/pull/393
