### ISSUE TITLE
'Upload' and 'New folder' buttons don't work

### ISSUE THREAD

**Issue by Xarthisius** [whole-tale/dashboard#17]
For some reason when I try them, the outgoing REST request is malformed:

```
https://girder.wholetale.org//api/v1/folder?parentType=user&parentId=null&name=test
```
specifically `parentId` is not set. Happens both for uploading a file, and creating new folder (tried both in the  Home section of upload/data tab)

**Comment by ian-taylor** [comment]
Yep, this is because we’ve move to using the home directory and the parent type is a “user” ID. Adam is working through these issues at the moment,

**Comment by abrinckm** [comment]
Works now with new browser after commit [6474e56](https://github.com/whole-tale/dashboard/commit/6474e563cf4725ad15dbd89a005f5f289a40d632)

However, unsure of where we should allow uploading files and creation of folders. For now, the only place we can do this is inside the notebooks, private, and public folders. Unsure about whether we allow this inside of registered folders or inside root home directory.
