### ISSUE TITLE
Add the `Entry Point` Radio Buttons to the File Browser

### ISSUE THREAD

**Issue by ThomasThelen** [whole-tale/dashboard#172]
We're going to let the user specify the entry point to the tale (which file they should run). We need to add this to the file browser (in the publishing dialog). The buttons should be across the file level, and not allowed for folders.

Note that this is probably not the file browser that the user uses when the user selects data in the `Compose` area.

**Comment by abrinckm** [comment]
I see a priority tag on this. Did you want this feature done by mid July? I don't remember this being discussed as a feature for the MVP. If it is a priority we'll need to adjust and make room in our sprint.

**Comment by abrinckm** [comment]
Nevermind, I can see you self-assigned. This one is all yours. :)

**Comment by ThomasThelen** [comment]
Oops I should have clarified this was going in the publishing modal and is probably not the same file browser as the one in the `Compose` area.

**Comment by ThomasThelen** [comment]
Adam did this in 7eb57ef14ab6d274f2e2cd2bd483ac62b46d57b3
