### ISSUE TITLE
Icons bounce too much

### ISSUE THREAD

**Issue by MatthewTurk** [whole-tale/dashboard#177]
On the new UI, the tale tiles bounce/zoom all the time.  For instance, if I'm filtering, as I type, each keystroke updates the list of tales and thus each keystroke results in every tale tile bouncing.

**Comment by cyberdante** [comment]
I agree that the icons are too "bouncy". When should the animation be triggered? When they are loaded only? Or when they are loaded and also when the number of `tales` changes by the composition of a new tale or the deletion of an existing one?

**Comment by MatthewTurk** [comment]
If it's easier for now, disabling the bouncing would be a fine stopgap.

**Comment by cyberdante** [comment]
Sounds good
