### ISSUE TITLE
Tales Launched in `Browse` are not Immediately Reflected in the `Launched Tales` Widget

### ISSUE THREAD

**Issue by ThomasThelen** [whole-tale/dashboard#179]
After launching a tale from the `Browse` page, I noticed that the tale did not show up in the `Launched Tales` widget (see image). Once I navigate away, or refresh the page the tale is properly shown in the widget.

To Reproduce: 
   1. Go to https://newdashboard.dev.wholetale.org/browse
   2. Click `Launch` on any tale
   3. Note that the tale has launched, but isn't in the `Launched Tales` widget
   4. Refresh the page
   5. Note that it shows up
Build: `7199664`

<img width="1653" alt="screen shot 2018-07-02 at 9 22 18 am" src="https://user-images.githubusercontent.com/9289652/42175417-2c408878-7dda-11e8-8ef5-5ef0481b3c1c.png">

**Comment by swyngaard** [comment]
This is most likely because the way in which tales are instantiated has recently changed. Resolving #140 will probably fix this issue. Thanks for reporting, it's been really helpful.

**Comment by swyngaard** [comment]
This should be resolved now (see this commit for details [c37751e](https://github.com/whole-tale/dashboard/commit/c37751e3efd336a8d6ca415046fbce6f37d144c7)). Please test and confirm.

**Comment by ThomasThelen** [comment]
Can confirm this is no longer in issue in build c37751e

**Comment by swyngaard** [comment]
Thanks for following up!
