### ISSUE TITLE
Lingering Checkmark in Data Browser

### ISSUE THREAD

**Issue by ThomasThelen** [whole-tale/dashboard#181]
I noticed that I can have tick mark on a folder without any data inside being selected.

To Reproduce:
   1. Go to `https://newdashboard.dev.wholetale.org/compose`
   2. Click a checkbox next to a folder in the Data Browser
   3. Navigate inside the folder
   4. Un-select all the files
   5. Navigate a level out
   6. See the the folder still has a tick mark on it

Seen in build `7199664 `

![screen shot 2018-07-02 at 11 25 09 am](https://user-images.githubusercontent.com/9289652/42180070-b0f7ea6a-7dea-11e8-9468-ab34a2c06308.png)
![screen shot 2018-07-02 at 11 25 23 am](https://user-images.githubusercontent.com/9289652/42180071-b1127d26-7dea-11e8-95d5-040b29251906.png)

**Comment by abrinckm** [comment]
Will look into it

**Comment by ThomasThelen** [comment]
We no longer have the data browser component in the dashboard, having been replaced with the data selection modal on the Run page.
