### ISSUE TITLE
Dashboard Only Displays 'Browse`

### ISSUE THREAD

**Issue by ThomasThelen** [whole-tale/dashboard#189]
As mentioned on the July-9 2018 dev call this is a bug where something is getting left over in the local storage.
Workaround: Clear your cache/local storage

If you see this behavior-please post on the slack channel before clearing your cache.

<img width="1680" alt="screen shot 2018-07-09 at 12 22 29 pm" src="https://user-images.githubusercontent.com/9289652/42471854-128eeb1e-8374-11e8-8e7c-9f4a7e338bfd.png">

**Comment by abrinckm** [comment]
If using Chrome please open dev tools -> Application -> Storage -> Local Storage -> localhost and copy paste all the information you see there. Thank you!

**Comment by ThomasThelen** [comment]
Closing this since we're already tracking the app storage issues.
