### ISSUE TITLE
Manage page shows workspace folder

### ISSUE THREAD

**Issue by craig-willis** [whole-tale/dashboard#194]
When first accessing the Manage page after logging in, the `Data`, `Home` and `Workspace` folders are displayed.  Since we do not yet have support for Workspaces, this is likely going to be confusing for some users.  It also seems strange to show the Home and Data tabs on the left with the Home and Data folders on the right.

<img width="864" alt="screen shot 2018-07-12 at 7 47 15 am" src="https://user-images.githubusercontent.com/4334350/42634057-d45919ec-85a7-11e8-8db7-9054c7ce30d1.png">

**Comment by craig-willis** [comment]
Appears to be working as expected. When I first login and go to Manage, it now defaults to the Home folder.  Thanks @abrinckm

**Comment by craig-willis** [comment]
Actually, I am seeing one oddity.  When I first login, I see only the folder in Home, but if I refresh I see files:

![screen shot 2018-07-19 at 10 00 39 am](https://user-images.githubusercontent.com/4334350/42950920-a7b9ac4c-8b3a-11e8-9597-5949b8127ca3.png)
![screen shot 2018-07-19 at 10 00 48 am](https://user-images.githubusercontent.com/4334350/42950929-abcb9a3e-8b3a-11e8-853e-cbe651ae2a4c.png)

**Comment by abrinckm** [comment]
my initial fix broke something.

**Comment by abrinckm** [comment]
should be fixed in commit [ceac1b7](https://github.com/whole-tale/dashboard/commit/ceac1b71c16527eb3ed78be9b1271999a96fbe80)

**Comment by craig-willis** [comment]
I'm seeing folders and files now in `ceac1b7` on dev.
