### ISSUE TITLE
Add More Information to the Data Registration Dialog

### ISSUE THREAD

**Issue by ThomasThelen** [whole-tale/dashboard#198]
People have been confused about which data repositories they can register their data from. Add some information to the modal that links to the documentation where the sources are outlined.

This was done in commit 1053701651ace195842bbfdc4fe4497999445c2a

**Comment by craig-willis** [comment]
@ThomasThelen 
Discussing with @Xarthisius, the preference for v0.4 is to display the text either above or below the search bar. For example:

![image](https://user-images.githubusercontent.com/4334350/42832236-3ac3984e-89b6-11e8-81db-085303922310.png)

**Comment by ThomasThelen** [comment]
This has been deployed; if all looks well this can be closed.
