### ISSUE TITLE
Multiple issues with Dashboard on Firefox

### ISSUE THREAD

**Issue by craig-willis** [whole-tale/dashboard#202]
Seeing multiple issues with Dashboard under Firefox:

* Clicking on file name for  context menu results in `TypeError: a.transitionToRoute is not a function` in console
* Can't click on Tale in Launched Tales results in  `ReferenceError: event is not defined`
* iframes not working Ligo tale shows `The compute environment for this Tale must run in a separate browser window. Clicking `Go to new window` does nothing
* "Report a problem" link to Github doesn't work

**Comment by craig-willis** [comment]
@abrinckm Are you saying that you were not able to replicate the problem locally?  Try production to see what I'm reporting -- it's certainly still there for me.

**Comment by abrinckm** [comment]
Okay. I pushed a fix to newui brand in commit [b49fff9](https://github.com/whole-tale/dashboard/commit/b49fff982f595e8a946fa85866406f3377e5b7a1)

You'll need to redeploy and test. 

That commit should resolve: 
1. can't click on tale in Launched Tales
1. clicking on `New Window` does nothing.

Although Iframes not working in firefox may still be an issue

**Comment by abrinckm** [comment]
@craig-willis Actually wait until @cyberdante pushes his work. His work includes some fixes as well.
