### ISSUE TITLE
'Back' button on a Tale view shouldn't allow to leave the dashboard

### ISSUE THREAD

**Issue by Xarthisius** [whole-tale/dashboard#210]
Currently if you follow a direct link to a Tale view e.g. [here](https://dashboard.wholetale.org/tale/view/59f0b91584b7920001b46f2e) and you subsequently hit 'Back' button there, you're redirected to a page where you came from. This behavior seems to be confusing for users (see whole-tale/whole-tale#29).
I'd suggest that we check if 'Back' would cause user to leave the dashboard, and if so, default to 'Browse' view.

**Comment by abrinckm** [comment]
Seems to be a new issue where the back button doesn't seem to work at all.

**Comment by bodom0015** [comment]
No longer an issue - newly refactored view does not use `window.history.back()`
