### ISSUE TITLE
No way to launch an instance from the Tale 'view'.

### ISSUE THREAD

**Issue by Xarthisius** [whole-tale/dashboard#211]
Tale view lacks "run" button.

**Comment by cyberdante** [comment]
@Xarthisius is `Run` the same as `Launch` in this case? I have been working on this by way of recovering some of the pre-existing UI that have been commented (although the logic is different now)

**Comment by ThomasThelen** [comment]
Tested this and it looks good!

**Comment by ThomasThelen** [comment]
This was tested but I believe is waiting on ND to close it during spring planning. @cyberdante is it okay to close this?

**Comment by cyberdante** [comment]
@abrinckm will close this by the end of our sprint. Thanks @ThomasThelen
