### ISSUE TITLE
Remove `newUIMode` from Local Storage

### ISSUE THREAD

**Issue by ThomasThelen** [whole-tale/dashboard#212]
I don't think we need this any more. There are only a few files that reference this-the user facing part is in `application.hbs`.

**Comment by cyberdante** [comment]
Fixed in commit [#2e09d09](https://github.com/whole-tale/dashboard/commit/2e09d098b7d675be60578f068baa2d1209c1a1b8). Changes are now in `orcid_changes` branch, ready to be merged.
