### ISSUE TITLE
Refactor Modals to Use ember-modal-dialog

### ISSUE THREAD

**Issue by ThomasThelen** [whole-tale/dashboard#218]
We should refactor our modal dialogs to use `ember-modal-dialog`. This will allow us to pass data to the modal (like tale id).

See https://dockyard.com/blog/2015/06/08/a-clean-pattern-for-modal-dialogs for more information on how to do this.

**Comment by cyberdante** [comment]
Tommy, this is just a suggestion: our modals' current code is already in Production. We don't want to introduce major (possibly braking) changes that we have to test throughout the app. Small wins. Change the modal you need to modify or are working on currently, test it, make sure you know how this new component that you're introducing works, push that code, and only **then** replace the rest of the modals using the `ember-modal-dialog`.
