### ISSUE TITLE
'Report a Problem' button on https://dashboard.wholetale.org/browse doesn't go anywhere

### ISSUE THREAD

**Issue by setgree** [whole-tale/dashboard#219]
<img width="614" alt="screen shot 2018-08-01 at 3 26 03 pm" src="https://user-images.githubusercontent.com/9850322/43543857-4286f7d4-959f-11e8-84b2-13ee051d3695.png">

Clicking it goes nowhere.

**Comment by Xarthisius** [comment]
Hi @setgree,
are you using Firefox? We identified (and fixed) a couple of issues (#202) but it hasn't been deployed to our production instance yet.

**Comment by cyberdante** [comment]
This is a dup of #209

**Comment by setgree** [comment]
It was indeed Firefox @Xarthisius, and sorry about that @cyberdante , I had thought I searched but must have overlooked #209.
