### ISSUE TITLE
Tale Run view missing top bar with Edit Tale Info / Publish buttons

### ISSUE THREAD

**Issue by amoeba** [whole-tale/dashboard#238]
@ThomasThelen pointed this out privately this morning:

The current Run view (on `dashboard.dev`) is missing a way for the user to Publish. See:

<img width="1089" alt="screen shot 2018-08-13 at 10 35 18 am" src="https://user-images.githubusercontent.com/563/44050871-be2711dc-9ee4-11e8-99dd-e9a70d93eec3.png">

Looking at the Invision mockups, this is supposed to look more like:

<img width="739" alt="screen shot 2018-08-13 at 10 36 06 am" src="https://user-images.githubusercontent.com/563/44050875-c1101146-9ee4-11e8-8517-5f996424753e.png">

For 0.5 and to get Publishing working nicely throughout the app, we should get this missing bar back in so the user can Publish from the Run view. Later on, we can look to finishing the whole feature shown in the Invision mockups which involves adding an accordion-style mechanism to edit Tale info from the Run view.

**Comment by amoeba** [comment]
Got the bulk of this done yesterday,

<img width="823" alt="screen shot 2018-08-16 at 10 08 21 am" src="https://user-images.githubusercontent.com/563/44226879-b796f200-a13d-11e8-9da7-59e29e74f92c.png">

just debugging some weirdness with the publish modal I caused.

**Comment by amoeba** [comment]
I've been trying to link this view into the app-level `showModal` but without luck 

https://github.com/whole-tale/dashboard/blob/a0d5c4074b6bd471cb8899d9871d15c4bd49e58e/app/routes/application.js#L44

@swyngaard has been helping but I haven't had any luck just yet.

**Comment by amoeba** [comment]
We chatted about this on today's dev call and @cyberdante said he'd take a look since he was familiar with the `showModal` feature implemented in https://github.com/whole-tale/dashboard/blob/a0d5c4074b6bd471cb8899d9871d15c4bd49e58e/app/routes/application.js#L44. My attempt from @swyngaard 's suggestions was in 8d4d2584ae4849781cbb108e32eda57428252788

**Comment by cyberdante** [comment]
What's the status of this issue after I helped with the showing of the modal? Is there anything else I can help with?

**Comment by amoeba** [comment]
I haven't taken a look yet but when I do I'll update this Issue.

**Comment by amoeba** [comment]
@ThomasThelen and I just chatted and it looks like he got it all hooked in. @ThomasThelen can you verify that and close this. Also wouldn't hurt to delete my run-page-improvements branch if you don't need it anymore. Let me know and I can do that or you can.
