### ISSUE TITLE
Can't delete running instances

### ISSUE THREAD

**Issue by amoeba** [whole-tale/dashboard#246]
Just ran into this: I can't delete any of my running instances on https://dashboard.dev.wholetale.org. I see a JS error in my console of `wholetale-4d7de71586e46a8dc2a3cb07f6ae5a87.js:266 Uncaught TypeError: e.destroyRecord is not a function`.

Steps to reproduce:

- Visit https://dashboard.dev.wholetale.org
- (I already had two running instances)
- Navigate to the Run page
- Click the X button in the Launched Tales pane
- Click Yes at the "Really Delete instance?" modal
- Observe:
	- Instance is not removed
	- JS error in console: `Uncaught TypeError: e.destroyRecord is not a function`

Can anyone reproduce this?

**Comment by ThomasThelen** [comment]
I wonder if this is related to #213-I get the same error when deleting a tale. On the delete modal, do you see the tale name as `""`?

**Comment by amoeba** [comment]
Ah, yep. Should we leave this Issue open until we get tale deletion back working or do those other two issues suitably cover this one?

**Comment by ThomasThelen** [comment]
I think those two cover it. While testing #213 I also see `e.destroyRecord`

**Comment by amoeba** [comment]
Great, thanks.
