### ISSUE TITLE
Open/Select Files Already in Tale

### ISSUE THREAD

**Issue by ThomasThelen** [whole-tale/dashboard#250]
The file picker currently selects the files that are in the tale with [getTaleFiles](https://github.com/whole-tale/dashboard/blob/master/app/components/ui/files/file-picker/component.js#L30). The issue is that the first time the dialog is opened, the files are recorded but the check boxes aren't checked.

**Comment by ThomasThelen** [comment]
Amendment to the above.

I would check beforehand what `getTaleFiles` is returning on the modal open just to make sure the right things are initially selected. I know I said we're grabbing the right files, but after investigating I think that we should additionally be selecting everything the Tale's n immutable folders.

**Comment by amoeba** [comment]
That makes sense to me. It seems like the only thing that should be selected should be the immutable content the backend set aside when the instance was created?

> I know I said we're grabbing the right files, but after investigating I think that we should additionally be selecting everything the Tale's n immutable folders.

This reads like you're thinking there are other files besides the immutable files that should be auto-selected. Is that right and, if so, what are they? We probably talked about this before so I apologize if I I'm forgetting something.

**Comment by amoeba** [comment]
Ah, I see the code is selecting files in the tale folder. What's usually in there? In my testing it's empty.

**Comment by amoeba** [comment]
Hey @ThomasThelen I didn't get a chance to talk with you about this but I ended up with doing 262dfdad2c1bac360198d66faa018a622afadf7c to address this. In my limited testing it works as I expect but I wanna be sure what I expect is right. Could you take a look? One thing this isn't doing is selecting all child elements in a folder but it does check the folder.

**Comment by ThomasThelen** [comment]
Selecting files is no longer an issue since we're implementing the picker as a read only. See issue #305 for more information.
