### ISSUE TITLE
Resize Compute Environment

### ISSUE THREAD

**Issue by ThomasThelen** [whole-tale/dashboard#251]
![screen shot 2018-08-27 at 2 19 25 pm](https://user-images.githubusercontent.com/9289652/44686839-50fab980-aa04-11e8-9bb6-73f2701726c4.png)

It looks like the paddleboard pushed the compute environment down, and in the screenshot above you can't see the full output at the bottom left.

**Comment by cyberdante** [comment]
The height of the paddleboard is calculated taking into consideration the whole vertical height (100vh) and the height of the different bars: header, footer, title, and obviously the paddings. That’s an easy fix. I’ll take it ;-)

**Comment by cyberdante** [comment]
Just finished this. Please, @ThomasThelen verify that the changes are working correctly in `orcid_changes` branch.

**Comment by cyberdante** [comment]
<img width="1678" alt="screen shot 2018-08-27 at 9 40 57 pm" src="https://user-images.githubusercontent.com/20361247/44695596-f41df400-aa41-11e8-90db-ce7bf6cbfcf7.png">
