### ISSUE TITLE
Fix OAuth Redirect

### ISSUE THREAD

**Issue by ThomasThelen** [whole-tale/dashboard#253]
It looks like the ORCID OAuth is redirecting to the production dashboard instead of development.

**Comment by cyberdante** [comment]
I added a config value for this in ‘config/environment’. Check that the values for dev and production are correct, @ThomasThelen

**Comment by ThomasThelen** [comment]
I checked it out and it all looks good!
Looking at the [dockerfile](https://hub.docker.com/r/wholetale/dashboard/~/dockerfile/) I suspect we're actually setting it to `production`.
`RUN ./node_modules/.bin/ember build --environment=production`

**Comment by cyberdante** [comment]
We should not change it in the `dockerfile`. This should be set correctly, and the file you're referring to is for building the prod environment precisely, most likely taking the latest commit from the `master` branch. A different `dockerfile` should be set for [development](https://dashboard.dev.wholetale.org/) with the proper environment config values.

**Comment by Xarthisius** [comment]
These are two different things. Ember's 'production'/'dev' have nothing to do with our deployments. Specifically ember's 'development' sets `ENV.dev` to `true`, which caused us a lot of headaches in the past.

The way it's being done right now, we're using placeholder:
https://github.com/whole-tale/dashboard/blob/master/config/environment.js#L97
that's set during container initialization:
https://github.com/whole-tale/dashboard/blob/master/docker-entrypoint.sh#L3

Properties that can easily change (urls for girder or dashboard itself are a good example) cannot be hardcoded into the code. They should always be somehow configurable during the runtime, with setting via ENV var being a preferred method.

**Comment by cyberdante** [comment]
And that was precisely my approach. I added `ENV.wholeTaleHost` within [config/environment.js](https://github.com/whole-tale/dashboard/blob/orcid_changes/config/environment.js#L93) for `development` and a different value for production in the same file, [here](https://github.com/whole-tale/dashboard/blob/orcid_changes/config/environment.js#L103).

**Comment by Xarthisius** [comment]
I wasn't clear, when I said "ENV var" I meant host/shell environment variable that runs a given instance of dashboard, not the Ember struct.

We run at least two "production" (in ember-sense) dashboards: .prod and .stage. At one point in time we also had .wholetale.xyz. When we test PRs we sometimes launch additional deployments. Unless we were able to modify those settings during runtime, we would need to maintain N docker images and that's not feasible.

**Comment by cyberdante** [comment]
I believe that's correct @craig-willis

**Comment by ThomasThelen** [comment]
This was fixed in Pull Request #20
