### ISSUE TITLE
Disable Publish & Edit Buttons in Run Paddleboard on Empty Tale

### ISSUE THREAD

**Issue by ThomasThelen** [whole-tale/dashboard#255]
![screen shot 2018-08-27 at 6 01 06 pm](https://user-images.githubusercontent.com/9289652/44736138-4b07e580-aaa3-11e8-9ce5-de06e8590384.png)

We should probably grey out/hide the two buttons when the `/run` page is visited if a tale hasn't been selected. 

This can be done by checking the model for the tale ID. If it doesn't exist, disable the buttons.

**Comment by cyberdante** [comment]
Actually, the `run.view` route will have a selected tale always, unless the tale ID is invalid or non-existent. The `/run` route will never have a selected tale, meaning that whole bar would not be showing in that case.
