### ISSUE TITLE
Create/Implement Edit Tale Dialog/Page

### ISSUE THREAD

**Issue by ThomasThelen** [whole-tale/dashboard#256]
The `Edit Tale` button should display a page that's yet to be created (this issue).

Note that this isn't required for 0.5. The user is also able to modify this Tale information through the Tale View. 

This dialog is almost 1-1 with the content in the Tale View, and should use the existing components from there.

From the invision mockup, 
![screen shot 2018-08-28 at 9 47 04 am](https://user-images.githubusercontent.com/9289652/44737619-5eb54b00-aaa7-11e8-8114-7ff0069d241b.png)

**Comment by cyberdante** [comment]
What is needed here is to just "componentize" the `tale/view/{taleId}` route to move away from controllers as much as possible. We need to create a component and then move our controller's logic there.

**Comment by ThomasThelen** [comment]
With the latest round of mockups, it would appear that this functionality is no longer required. Instead of an edit button with the Tale information, the information is displayed under the `metadata` section, shown below.
The task for that refactor is #285

![screen shot 2018-11-14 at 2 00 59 pm](https://user-images.githubusercontent.com/9289652/48515527-cad95c80-e815-11e8-9668-d5b1317882f6.png)
