### ISSUE TITLE
File operations menu hides under sidebar (fixed menu)

### ISSUE THREAD

**Issue by Xarthisius** [whole-tale/dashboard#26]
![wtbug01](https://cloud.githubusercontent.com/assets/352673/24967800/e7a60684-1f70-11e7-9f68-c48e69183ba0.png)

**Comment by ian-taylor** [comment]
I cannot repeat this on safari or chrome on my mac. Can you please state the OS, browser and browser version ?

**Comment by Xarthisius** [comment]
Chrome: `Version 58.0.3004.3 (Official Build) dev (64-bit)`
Linux: `Linux shakuras 4.9.4-gentoo #1 SMP Wed Jan 18 15:36:21 CST 2017 x86_64 Intel(R) Core(TM) i7-5500U CPU @ 2.40GHz GenuineIntel GNU/Linux`

**Comment by ian-taylor** [comment]
Is the browser full size or did you reduce the size to responsive mode?

**Comment by Xarthisius** [comment]
Full size, single window 3200x1800. I have a HiDPI maybe that's messing it up?

**Comment by ian-taylor** [comment]
Added a fix that may solve this but could not repeat it so needs testing when the push is deployed on dev. If it works, please close this issue, if not, we'll try and replicate some other way.

**Comment by Xarthisius** [comment]
Still the same, but don't worry about it now. AFAIU that menu's gonna be gone anyway

**Comment by abrinckm** [comment]
Right, that context menu doesn't work in Firefox. I'm going to implement a toolbar to replace it soon.

**Comment by abrinckm** [comment]
#27

**Comment by ian-taylor** [comment]
I agree. The right click context menu is nice when it works but getting it consistent is hard. It also doesn't work with ctrl click on a mac. Let's try another approach and see how we like it.

**Comment by abrinckm** [comment]
Replaced the context menu with a dropdown menu in commit [7b3582b](https://github.com/whole-tale/dashboard/commit/7b3582b9eb4296b8e36a822f8ed5cd67478bc1ee)
