### ISSUE TITLE
Should registering the same dataset multiple times result duplicate/replace existing copies?

### ISSUE THREAD

**Issue by amoeba** [whole-tale/dashboard#267]
I've noticed that, if you register the same dataset multiple times, you get multiple copies on your Data folder.

<img width="719" alt="screen shot 2018-09-13 at 9 21 11 am" src="https://user-images.githubusercontent.com/563/45494322-6119d500-b736-11e8-81bd-9918f11ce653.png">

My expectation was that I wouldn't see any duplication. For DataONE, registrations are long-lived and the bytes behind identifiers are immutable so registering the same dataset multiple times results in identical copies (so long as our implementation of registration stays the same). For other sources, this may _not_ be the case, such as HTTP registration.

Can we discuss the behavior of the system here?

Options I can think of include:

- For DataONE and other immutable sources, don't re-register, for others, do?
- Compare/diff existing registration with the new one and only make a copy if different? This doesn't scale well unless we store the total size of the registration somewhere.
- Never re-register
- Always re-register

This decision interacts with our decision to make data registration system-global or user-local.

**Comment by Xarthisius** [comment]
We prevent duplicates in a collection that holds initial copy (https://girder.dev.wholetale.org/#collection/596793f2ebde2c0001b03dbe/folder/596793f2ebde2c0001b03dbf), but similar mechanism is not implemented for "copy to Home" part. I always thought of it as requesting for a "fresh copy" of the original dataset.

**Comment by amoeba** [comment]
Oh, so is it right to say that this Girder collection only has one reference and that something else has the duplicates? What explains why I see duplicates in that list?

**Comment by Xarthisius** [comment]
It's your personal "data"  folder  that has duplicates. System-wide "data" is not exposed in the UI right now (It used to be "datasets" page in  pre-MVP version of the dashboard). I don't know what are the plans for that part, I haven't seen it in  the mockups

**Comment by amoeba** [comment]
Roger that. Is the current behavior beneficial in any way or do you think it's an more sensible default to _not_ duplicate? 

I'm thinking it's potentially confusing for the user is this situation where I have :

<img width="1010" alt="screen shot 2018-09-13 at 9 55 57 am" src="https://user-images.githubusercontent.com/563/45496992-3d598d80-b73c-11e8-9d35-6f3c92fd95db.png">

**Comment by ThomasThelen** [comment]
The new way of adding registered data via the workspace/ my data modal prevents multiple copies of the same dataset being added. I think this can be closed

**Comment by Xarthisius** [comment]
Fixed in https://github.com/whole-tale/girder_wholetale/pull/205
