### ISSUE TITLE
Validate local storage state and improve error handling

### ISSUE THREAD

**Issue by craig-willis** [whole-tale/dashboard#268]
We've encountered yet another problem where invalid local storage state prevented users from accessing part of the system.  In this case, the "Manage" tab was failing because of a 404 on the `currentFolderId` in local storage.

This particular case can be reproduced by the following steps:
* Go to Manage > Home, create a folder called test
* Start a tale. In the tale go to home and delete the test folder
* Open Developer tools
* Go back to Manage

You'll see 400 errors for the folder, since the `currentFolderId` in local storage does not exist.

This is one instance of a problem we've seen a number of times -- the local storage state is invalid rendering parts of UI unusable with no error indication.  We need to either add validation/error handling to confirm stored IDs exist (or not rely on local storage).

**Comment by cyberdante** [comment]
@craig-willis I agree that we need a better management of the `local storage`, but I was not able to reproduce this issue particularly following your steps. I even called Sebastian to look over my shoulder in case I was missing something with no results. Will try to add a mechanism to reroute from `manage.view` to `manage.index` whenever we get this type of issue. I implemented the same thing for the run page earlier this week.

**Comment by craig-willis** [comment]
@cyberdante Sorry, I missed a key step in the description:

* Go to Manage > Home, create a folder called test
* **Select the test folder**
* Start a tale (e.g., Jupyter). In the tale go to `home` and delete the test folder
* Open Developer tools
* Go back to Manage

**Comment by ThomasThelen** [comment]
It looks like issue #189 is caused by this, so I'm going to link it here.

**Comment by craig-willis** [comment]
@bodom0015 This would be really nice to fix for the upcoming v0.5 release.  Would you be willing to look into the problem? It's pretty pervasive, but maybe we could fix some of the obvious cases quickly.
