### ISSUE TITLE
Tale deletion takes the user to an unsupported page

### ISSUE THREAD

**Issue by cyberdante** [whole-tale/dashboard#270]
![Screen Shot 2018-09-17 at 11.13.16 AM.png](https://images.zenhubusercontent.com/5af1b4ba4b5806bc2bd249f9/7bc9a105-9600-4b03-9167-9f428839c202)

**Comment by ThomasThelen** [comment]
I tried reproducing this on chrome and firefox and was unable to. I tested on build `5eae564`

**Comment by Xarthisius** [comment]
Can't reproduce, please reopen if that's still a valid issue.
