### ISSUE TITLE
Some modals appear 50% shifted to the middle of the screen

### ISSUE THREAD

**Issue by cyberdante** [whole-tale/dashboard#271]
The Delete modal also appears with the wrong height in these cases and do not show the name of the tale being deleted.

![Screen Shot 2018-09-17 at 11.18.52 AM.png](https://images.zenhubusercontent.com/5af1b4ba4b5806bc2bd249f9/a7756d54-9f07-446d-add4-1ac213ce4a48)

**Comment by cyberdante** [comment]
If a tale that has running instances is attempted to be deleted, a message will inform the user that it is impossible to delete that tale. @Xarthisius, you mentioned that this should _also_ be handled by the backend?

**Comment by ThomasThelen** [comment]
It looks like the code change re-positioned some of the other modals, seen below. The delete modal looks to be the right size, but the positioning is off.

<img width="1678" alt="screen shot 2018-09-20 at 10 35 02 am" src="https://user-images.githubusercontent.com/9289652/45836173-ee25d680-bcc0-11e8-96cd-f40b22f4851f.png">
<img width="1680" alt="screen shot 2018-09-20 at 10 35 26 am" src="https://user-images.githubusercontent.com/9289652/45836174-ee25d680-bcc0-11e8-955f-2a241082315c.png">
<img width="1675" alt="screen shot 2018-09-20 at 10 34 41 am" src="https://user-images.githubusercontent.com/9289652/45836179-f120c700-bcc0-11e8-8737-9fd967bdb03e.png">

**Comment by cyberdante** [comment]
Will take a look shortly @ThomasThelen. Thanks for pointing out to this

**Comment by craig-willis** [comment]
@cyberdante  or @ThomasThelen -- @bodom0015 was looking at this and noticed that removing the `legacy` class seems to have solved it.  It looks like this may be related to a change in `semantic-ui-css`

https://github.com/Semantic-Org/Semantic-UI-CSS/blob/a34845ec7cf19a15daa575ee6682cfa73525b48b/components/modal.css#L324

Just curious if you have any thoughts on this.  Are we intentionally using the `legacy` or is this related to changes in package versions.

**Comment by ThomasThelen** [comment]
I'm not sure if we're supporting legacy,

We have a chunk of code we try to apply to all modals,
```
.ui.modal {
    position: fixed;
    top:    0;
    left:   0;
    right:  0;
    bottom: 0;
    margin: auto !important;
  }
```

BUT. Not all modals are `ui.modal.blablahblah`, see below.

```
  .newfolder,
  .delete-modal,
  .ui.dataone.modal,
  .warning-modal,
  .ui.compose-error.modal
```

This doesn't explain why things were working, and then stopped, but it looks like if we force the `.ui.modal` css onto the troublesome modals (the second list), it works.

```
.ui.modal {
    position: fixed;
    top:    0;
    left:   0;
    right:  0;
    bottom: 0;
    margin: auto !important;
  }
  
  .newfolder,
  .delete-modal,
  .ui.dataone.modal,
  .warning-modal,
  .ui.compose-error.modal {
    height: 200px;
    top:    0;
    left:   0;
    bottom: 0;
  
    .header {
      .close.icon {
        position: absolute;
        right: 1rem;
        cursor: pointer;
      }
    }
  
    .image.content {
      height: auto;
      color: black;
    }
  }
```

<img width="1666" alt="screen shot 2018-11-14 at 2 39 29 pm" src="https://user-images.githubusercontent.com/9289652/48517472-425dba80-e81b-11e8-82de-186e95fcc7c9.png">
<img width="1657" alt="screen shot 2018-11-14 at 2 39 45 pm" src="https://user-images.githubusercontent.com/9289652/48517473-425dba80-e81b-11e8-9093-971cecafca87.png">
<img width="844" alt="screen shot 2018-11-14 at 2 40 19 pm" src="https://user-images.githubusercontent.com/9289652/48517474-425dba80-e81b-11e8-8f9d-47105ff93354.png">

**Comment by cyberdante** [comment]
@ThomasThelen did you end up forcing those classes for all modals to show up at the correct/expected position?

**Comment by ThomasThelen** [comment]
I ended up going one level of specification deeper in the css-so instead of saying `for all semanticui modals do this`, I said `for all semanticui modals with these classes, do this`. 

Anybody can easily use the default theme-ing by putting `ui modal` at the end of their modal class. If someone makes a modal and for some reason sees weird styling it should be pretty obvious that their class names are jumbled after looking at the style sheet.
