### ISSUE TITLE
Improve the file picker

### ISSUE THREAD

**Issue by abrinckm** [whole-tale/dashboard#272]

**Comment by ThomasThelen** [comment]
As part of #305, I'll take this!

**Comment by ThomasThelen** [comment]
The fix for this is to replace the picker with ember's jsTree. The tree takes structured JSON, which means that we need to map each folder/file to a particular format.

I initially did this in the UI, but ran into performance issues so I created an endpoint that returns the structure instead.

**Comment by ThomasThelen** [comment]
Closing this since we've since removed the file picker
