### ISSUE TITLE
Search for data modal badly positioned

### ISSUE THREAD

**Issue by hategan** [whole-tale/dashboard#298]
See attached screenshot. The buttons are hidden.
![data_modal_off](https://user-images.githubusercontent.com/7749227/49044730-82119400-f183-11e8-9e93-1fc546752e1e.png)

**Comment by Xarthisius** [comment]
Seems like https://github.com/whole-tale/dashboard/issues/271 is still an issue

**Comment by hategan** [comment]
Should have mentioned that this is with deploy-dev which uses wholetale/dashboard:latest which uses an unknown to me version of the dashboard.

**Comment by cyberdante** [comment]
@ThomasThelen have you seen this regression? Was this fixed before?
