### ISSUE TITLE
Preserve request route for non-logged-in users

### ISSUE THREAD

**Issue by craig-willis** [whole-tale/dashboard#299]
Currently, if a non-logged-in user attempts to access any route, such as https://dashboard.wholetale.org/compose, they are redirected to the login page and the requested route is lost, redirecting to browse.

Preserve the request route and add to the login redirect request.  This is primarily intended for the new "Analyse in WT" integration https://github.com/whole-tale/dashboard/pull/287, but should be implemented for all routes.

**Comment by ThomasThelen** [comment]
Linking to #300
