### ISSUE TITLE
Event Bus integration

### ISSUE THREAD

**Issue by Xarthisius** [whole-tale/dashboard#30]
It's not really integration, cause AFAICT events are already received on the dashboard side and printed to the console. It's more about creating nice UI for it.

**Comment by abrinckm** [comment]
There is now a notifications queue that displays pushed messages at most 1 every 6 seconds. 
I'm not sure what text should go into the notifications for registering a dataset. For now, it will display whatever message comes from the event bus.

**Comment by Xarthisius** [comment]
Fixed in cb906c5 . We can work on the details after we get feedback from ETeam
