### ISSUE TITLE
Tale Workspaces

### ISSUE THREAD

**Issue by craig-willis** [whole-tale/dashboard#301]
This epic covers tasks required to add "tale workspace" support based on the [design discussions](https://docs.google.com/document/d/1pl9FwVNeXyVVTccXLoTIeXsViWflbPpoQ5DLY44g5cw/edit#heading=h.y3lmftolmepl) and [mockups](http://www.crc.nd.edu/~kfurse/wholetale-css-mock-up-sui_f2018/run-files.html).  (Note that the goal is to "evolve" the current UI into the mocked-up UI over a series of releases by incrementally moving functionality from the current Manage tab to the Run tab).

* Add the tab component to the Run view.  Part of this work may already be complete based on https://github.com/whole-tale/dashboard/pull/297
* Add the "Interact" tab with current iFrame/popout
* Add the "Files" tab 
* Implement Tale Workspace view
* Update publish to use workspace

**Comment by bodom0015** [comment]
AFAICT, this was completed months ago
