### ISSUE TITLE
Implement "Tale Workspace" view

### ISSUE THREAD

**Issue by craig-willis** [whole-tale/dashboard#304]
Per the [mockup](http://www.crc.nd.edu/~kfurse/wholetale-css-mock-up-sui_f2018/run-files.html), the "Run" page will contain a "Files" tab that allows the user to manage files in the Tale workspace.    Note, this task does not cover the "home" or "external data" folders, which will continue to be supported through Manage (for now)

Goal: 
* The user can manage data in the workspace associated with the current tale. Supported actions on ~~Tale workspace include upload file, create folder, rename folder/files, remove folders/files, copy/move files from/to Home, copy data from other workspaces~~ (see https://github.com/whole-tale/dashboard/issues/337)

Completion criteria:
* [x] User can select "Files" tab to display contents Tale workspace
* [x] ~~User can manage files/folders using supported actions~~  (see https://github.com/whole-tale/dashboard/issues/337)
* [ ] Documentations updated
* [x] Manual test case provided

Note, backend support for workspaces should already be complete

**Comment by cyberdante** [comment]
@craig-willis - I have already put together this file/folder manager inside the tale workspace but I was wondering what the tale context means to this end. Which endpoint(s) should I be GETting from and POSTing to? I am currently loading the existing data from `/api/v1/folder?parentType=user&parentId={my_user_id}&name=Workspace&limit=0`

<img width="1564" alt="screen shot 2018-12-13 at 11 15 16 am" src="https://user-images.githubusercontent.com/20361247/49973306-933bfe00-ff02-11e8-82fc-a39659922fc8.png">

**Comment by cyberdante** [comment]
I'm going to test this second suggestion with the OpenAPI docs and get back to you if I miss anything, @Xarthisius. Thanks a lot!
