### ISSUE TITLE
Update publish to use workspaces

### ISSUE THREAD

**Issue by craig-willis** [whole-tale/dashboard#305]
Per the [design discussions](https://docs.google.com/document/d/1pl9FwVNeXyVVTccXLoTIeXsViWflbPpoQ5DLY44g5cw/edit#heading=h.y3lmftolmepl), publishing will operate on the Tale workspace and no longer allow the user to select data from Home. Note: there is still some discussion about whether to allow the user to select items to be published, so for now we will not implement this.

Goal: 
* During publish, the contents of the current Tale workspace are published. 

Completion criteria:
* [x] User can publish tale based on contents of current tale workspace
* [x] File picker is disabled (displaying a list of files without selection is OK)
* [x] Documentation updated
* [x] Manual test case provided

**Comment by ThomasThelen** [comment]
This was completed by bundling the workspace in the zipped Tale. During publication, we extract those files and upload them to DataONE. The file picker was also removed. The documentation was updated in [this](https://github.com/whole-tale/wt-design-docs/pull/81) merged PR
