### ISSUE TITLE
Tale-specific data selection

### ISSUE THREAD

**Issue by craig-willis** [whole-tale/dashboard#306]
This epic covers tasks required to allow users to add/remove data to a running Tale. This is based on the [Tale workspace](https://docs.google.com/document/d/1pl9FwVNeXyVVTccXLoTIeXsViWflbPpoQ5DLY44g5cw/edit#heading=h.y3lmftolmepl) design discussions, implementing the "Select Data" dialog and "external_data" tab in the [mockups](https://docs.google.com/document/d/1pl9FwVNeXyVVTccXLoTIeXsViWflbPpoQ5DLY44g5cw/edit#heading=h.y3lmftolmepl).

Tasks:
* Implement select data modal
* Add external_data tab to Run/Files tab

**Comment by bodom0015** [comment]
AFAIK, this has been fulfilled.
