### ISSUE TITLE
Implement Select Data modal with support for WT catalog data only

### ISSUE THREAD

**Issue by craig-willis** [whole-tale/dashboard#307]
Note:  Per the [design discussions](https://docs.google.com/document/d/1pl9FwVNeXyVVTccXLoTIeXsViWflbPpoQ5DLY44g5cw/edit#) the goal is for the "Select Data" modal to eventually be used in several places in the system -- for input data selection during compose as well as adding data to Tales.  The scope of this task is limited to adding data from the WT catalog (i.e., already-registered data) to an existing Tale.

Goal:
* The "Select Data" modal will allow the user to select data from the WT catalog (i.e., registered data). From the external_data tab, the user selects "+" to display the "Select Data" modal. The modal displays the contents of the WT catalog available to the user to be added to their Tale.  Assume that data is pre-registered via current Manage/Data tab. Ideally multiple selection is supported. 

Completion criteria:
* [x] User can browse available data from the global catalog or their registered datasets
* [x] User can select items from the catalog (parent component will be responsible for adding them to the current tale external_data collection)
* [x] Documentation updated
* [x] Manual test case provided

Note:
* Files folders are added/removed to session via `/api/v1/dm` endpoints. This supports add/remove (not checkbox in a hierarchy)
*

**Comment by abrinckm** [comment]
Completion Criteria has changed I believe.

During a brief discussion with Kacper and Craig, we decided that the modal will not be responsible for adding catalog items to the current tale external_data collection. The modal will simply return the list of selected items, and the parent component will be responsible for adding those items.

**Comment by abrinckm** [comment]
See [pull request](https://github.com/whole-tale/dashboard/pull/328)

**Comment by craig-willis** [comment]
Closing this.  Opened related  bug https://github.com/whole-tale/dashboard/issues/354
