### ISSUE TITLE
User can request to rebuild image from Tale workspace

### ISSUE THREAD

**Issue by craig-willis** [whole-tale/dashboard#309]
User story: The user has a running Tale instance and customizes the environment via apt.txt, requirements.txt, etc. They select the "Rebuild" menu item and a new image is built based on their environment customizations. The user is notified when the image build is complete (separate issue).

See [mockups](http://www.crc.nd.edu/~kfurse/wholetale-css-mock-up-sui_f2018/run.html). 

Completion criteria:
* [x] Add "..." menu
* [x] Add Rebuild menu item
* [x] Selecting "Rebuild" calls (API TBD) `/instance/{id}/build` (reference to girder_wholetale issue for rebuild API and repo2docker integration. Assume build creates job and triggers event on completion -- (Event name TBD) `intance.new.image`)
* [ ] Tale instance state is updated (requires new flag on model). When state is (TBD) "new image available", an indicator is displayed to the user.

**Comment by Xarthisius** [comment]
Done long time ago
