### ISSUE TITLE
User is notified of image build process and when new image is available

### ISSUE THREAD

**Issue by craig-willis** [whole-tale/dashboard#310]
User story: After selecting [Rebuild](https://github.com/whole-tale/dashboard/issues/309), the user should be notified based on the event stream that a new image is available regardless of what page they are on.

Completion criteria:
* [x] Progress bar displays during image build process
* [ ] TBD: when progress is complete, user can click to return to "Run" page to switch to new image
* [ ] Documentation updated
* [ ] Manual test case provided

**Comment by Xarthisius** [comment]
Done long time ago
