### ISSUE TITLE
0.5 RC Testing

### ISSUE THREAD

**Issue by ThomasThelen** [whole-tale/dashboard#327]
## 0.5 Testing
Now that we have a release candidate deployed, we should go through and make sure that the features are working properly under in production. 

- [x] **Test Dataverse Integration**
This release adds support for ingesting files from Dataverse packages. To confirm this feature is working, visit https://dev1.dataverse.org/dataset.xhtml?persistentId=doi:10.5072/FK2/EPNUKP and import the dataset via the `Explore` button. You should see the progressbar, and verify that it properly updates. You should also see `starbucks_us_locations2.tab` in the `data` folder in the running Tale.

- [x] **Test Data Registration Changes**
There was a small change to the backend data registration code. We should make sure that we're still able to register the following DataONE and HTTP files.
   1. https://search.dataone.org/view/doi:10.5063/F1Z60M87
   2. https://search.dataone.org/view/https://pasta.lternet.edu/package/metadata/eml/knb-lter-nwt/115/1
   3. https://search.dataone.org/view/doi:10.18739/A2CN6XZ7H
   4. https://raw.githubusercontent.com/whole-tale/dashboard/master/.travis.yml

- [x] **Basic Tale Use** See #332
We want to make sure we didn't have any regressions for launching and running Tales. Check a few of the standard Tales to make sure they are working properly.
   1. Launch the LIGO Tutorial
   2. Wait for the `Run` page to open
   3. Navigate to the main notebook and open it
   4. Run it

   1. Launch the Informatics-aided bandgap engineering for solar materials Tale
   2. Wait for the `Run` page to open
   3. Navigate to the main notebook and open it
   4. Run it

**Comment by pdurbin** [comment]
> visit [https://dev1.dataverse.org](https://dev1.dataverse.org/dataset.xhtml?persistentId=doi:10.5072/FK2/EPNUKP)

Hi! I'm thinking that it would be nice to let people test this from Dataverse's true "demo" site as well, so let me see what I can do to include loading up the Whole Tale external tool manifest on https://demo.dataverse.org as well.

Also, that "dev1" box isn't especially stable. You're welcome to use it for testing and I'll try to remember not to drop the database in the near future. 😄

**Comment by ThomasThelen** [comment]
Thanks for the heads up about `dev1`; I think deploying on the official demo server should be fine and sounds like the right way to go (Testing passes on `dev1`).

I'll mention @craig-willis and @Xarthisius to keep them in the loop about where this is deployed.

**Comment by pdurbin** [comment]
@ThomasThelen heads up that I just dropped the database on my "dev1" server so the Whole Tale button is gone. I just suggested putting it on the Dataverse demo site over at https://github.com/IQSS/dataverse/issues/5097#issuecomment-452313435 . If anyone needs the button back on my "dev1" server, please let me know. Thanks.

**Comment by ThomasThelen** [comment]
I re-tested this on 1/08/19 and didn't run across the previous issues that I had previously encountered. Closing.
