### ISSUE TITLE
Unable to close/destroy instance while it's spawning

### ISSUE THREAD

**Issue by Xarthisius** [whole-tale/dashboard#330]
Sometimes, when Tale instantiation fails, user is left with an entry in "Launched Tales" that has a spinner running indefinitely.

Expected result:
![close_tale](https://user-images.githubusercontent.com/352673/49815960-87014680-fd32-11e8-8a3d-0f0c34972049.png)

**Comment by ThomasThelen** [comment]
I think we've since improved the error handling to allow the user to stop/remove their instance if it gets caught in an error state (I forgot the timeout).
