### ISSUE TITLE
Ambiguity with Files tab Create Button

### ISSUE THREAD

**Issue by bodom0015** [whole-tale/dashboard#356]
The current implementation of the (+) button on the Files tab of the Tale view changes the behavior of the resulting modal. This is not made clear to the user, who may be confused when following our technical documentation. Hopefully with some minor UX changes, we can make it more clear to the user that their choice affects the behavior of the (+) button.

### Current implementation
<img width="830" alt="taledataselector-current" src="https://user-images.githubusercontent.com/1413653/51346250-c5d99900-1a62-11e9-9dde-c8bdff781e93.png">

### Proposed changes
The simplest proposed change would just move the selector up slightly, to make it more clear which contexts are affected by the choice on the left:
<img width="830" alt="taledataselector-proposed" src="https://user-images.githubusercontent.com/1413653/51346251-c5d99900-1a62-11e9-8ac1-d0f03456bafd.png">

Other options:
* Split up the (+) button functionality into a few more explicit presentation options (e.g. "Add External Data", "Add Tale Workspace Data", etc) - Note, we can still use the existing code for this, we just need to slightly adjust how the modal is called
* Add a slight animation to the (+) button when the selection changes, to indicate that its behavior has changed
* Adjust the (+) button so that it's functionality is less context-specific

**Comment by cyberdante** [comment]
@craig-willis @Xarthisius what's your take on this? I am willing to make the necessary changes, particularly the first/simpler/quicker to implement approach.

**Comment by bodom0015** [comment]
New mockups have addressed this ambiguity - Create button is now a part of the table whose contents change when the user switches navs
