### ISSUE TITLE
Remove Data panel from Compose and Run pages

### ISSUE THREAD

**Issue by craig-willis** [whole-tale/dashboard#362]
With the new Select Data modal in place (https://github.com/whole-tale/dashboard/pull/339), the Run > Data panel is no longer needed and should be removed.  The Compose > Data panel no longer functions as it used to and needs to be updated to use the Select Data modal.  For release v0.6, we'll just remove the Data panel from both Run and Compose pages.  A separate issue will be created to wire the Select Data modal to the Compose page ala the [mockups](http://www.crc.nd.edu/~kfurse/wholetale-css-mock-up-sui_f2018/browse-mytales.html) (select Create new tale).

Completion criteria:
* Data panel removed from Run and Compose pages.

**Comment by ThomasThelen** [comment]
I've played around with showing and hiding the Data panel already from the external launch feature. Feel free to assign this to me.

**Comment by craig-willis** [comment]
Just noting that I missed the "Input data: Select from Data panel" text on the compose page. If we don't implement https://github.com/whole-tale/dashboard/issues/366 for this release, we'll want to remove this.
