### ISSUE TITLE
Tale Workspaces > Select Data modal should list Tale names instead of IDs

### ISSUE THREAD

**Issue by bodom0015** [whole-tale/dashboard#364]
Currently, the Tale Workspaces "Select Data..." modal lists tales by ID. It would be more helpful to the users to list off the tale names here instead.

**Comment by bodom0015** [comment]
Looking into this now, but does not seem trivial to solve in the browser without reworking things significantly.

For example, see https://girder.dev.wholetale.org/#collection/59a4a0dc615678000159bbb4/folder/59a4a0dc615678000159bbb5

I am noticing that these IDs are also what is listed in Girder.. would it be acceptable to handle this conversion from `taleId` to `taleName` on the Data Manager / API side? Or perhaps this modal should just be looking at the `/tale` endpoint, instead of listing the contents from `/folder`?

It may be worth exploring this at the same time as #357, as these appear to be the same task in two different places - migrating one modal from using `/folder` and `/file` to use `/dataset` instead, and another from using `/folder` and `/file` to using `/tale` (or a new endpoint like `/workspace`) or something similar.

Thoughts?

**Comment by Xarthisius** [comment]
> It may be worth exploring this at the same time as #357, as these appear to be the same task in two different places - migrating one modal from using `/folder` and `/file` to use `/dataset` instead, and another from using `/folder` and `/file` to using `/tale` (or a new endpoint like `/workspace`) or something similar.

I think that approach would be best. If we could have the modal operate on `/blah` on the root level and expect to get a list of objects containing `_modelType` in `{'folder', 'item'}` it would work nicely in both scenarios
