### ISSUE TITLE
Add Select Data modal to Compose page

### ISSUE THREAD

**Issue by craig-willis** [whole-tale/dashboard#366]
Per issue #362, we removed the Data panel from the Compose page. Next, we want to enable Select Data modal as per the [Create new tale mockups](http://www.crc.nd.edu/~kfurse/wholetale-css-mock-up-sui_f2018/browse-mytales.html). Initially, this could be either the usual "+" button or the "Select Data" button per the mockup.

Use case:
1. User composes a Tale, enters name and selects environment
2. User selects "Select Data" to pre-select the external data that will be included with the Tale
3. "Select Data" modal operates as with the external data tab.  Items are added to the list of input data.
4. User selects "Launch Tale" and the tale is created, instance launched, with selected data available via /data and in the external data tab as expected.

Note that we must maintain existing "Launch in WT" support.

**Comment by bodom0015** [comment]
I think that we decided we weren't going to do this, right?
