### ISSUE TITLE
Can deselect instance when only one running

### ISSUE THREAD

**Issue by craig-willis** [whole-tale/dashboard#372]
When I have a single instance running, it is possible to "deselect" it from the right panel:

![screen shot 2019-01-31 at 11 58 21 am](https://user-images.githubusercontent.com/4334350/52074465-8b3a2b00-254f-11e9-9b79-dd137a54b808.png)

To repeat:
* Start an instance
* Click on the launched instance -- instance information displayed on left
* Click on it again -- "Choose from launched Tales panel" displays

Expected behavior:
* When I have one instance, I shouldn't be able to deselect.

But maybe this is just me.

**Comment by bodom0015** [comment]
No longer an issue, as the `tale-instances` panel is no longer used.
