### ISSUE TITLE
Dashboard displays useless error message 

### ISSUE THREAD

**Issue by craig-willis** [whole-tale/dashboard#373]
I see this periodically on my dev instance, but don't have a clearly reproducible case.  

![screen shot 2019-01-31 at 12 08 18 pm](https://user-images.githubusercontent.com/4334350/52075100-07813e00-2551-11e9-8f26-2505d3f86a02.png)

In this case, POST tale is returning a 400 error. 
```
Request URL: https://girder.local.wholetale.org/api/v1/tale
Request Method: POST
Status Code: 400 Bad Request
```

There is something more informative in the response:
 ```
{"message": "Invalid JSON object for parameter tale: 'involatileData' is a required property", "type": "rest"}
```

Expected behavior:
* Display informative message as a detail.

**Comment by ThomasThelen** [comment]
I believe there was a small period where both dataSet _and_ involatileData were required in `POST /dm/session`. I ran into this when I had the most recent dashboard instance but was behind on girder_wholetale.
It might be worth checking to see that your api parameters match the ones at https://girder.dev.wholetale.org/api/v1#!/dm/dm_createSession
