### ISSUE TITLE
Should Tales display a different icon than Folder in the Select Workspace Data modal?

### ISSUE THREAD

**Issue by bodom0015** [whole-tale/dashboard#377]
A simple question - we currently present files and folder with different icons in the UI. With the new "Tale Workspaces" modal, we are now listing Tales in this file browser, although never at the same time as other folders or items.

Do we want to customize the icon when listing Tales? Or could this be potentially confusing to the user, who may only be expecting to navigate files and folders?

Thoughts?

**Comment by Xarthisius** [comment]
[![](https://api.gh-polls.com/poll/01D2WXDXCVE91468BBTYK7QHB4/Keep%20the%20folder%20icon)](https://api.gh-polls.com/poll/01D2WXDXCVE91468BBTYK7QHB4/Keep%20the%20folder%20icon/vote)
[![](https://api.gh-polls.com/poll/01D2WXDXCVE91468BBTYK7QHB4/Use%20a%20custom%20Tale%20icon)](https://api.gh-polls.com/poll/01D2WXDXCVE91468BBTYK7QHB4/Use%20a%20custom%20Tale%20icon/vote)

**Comment by bodom0015** [comment]
Somewhat related to #388 - folders and workspaces now behave differently in the UI

**Comment by bodom0015** [comment]
Looked over some options briefly with @Xarthisius on Friday. Unfortunately [folder / folder-tree](https://fontawesome.com/icons?d=gallery&q=folder) are paid icons, but they would probably fit perfectly here.

Some free options:
* [newspaper / paperclip / scroll / map](https://fontawesome.com/icons?d=gallery&q=paper&m=free)
* [box / boxes / box-open / archive / parachute-box](https://fontawesome.com/icons?d=gallery&q=box&m=free) - parachute-box would be great for Tale sharing
* [folder / folder-open (transparent)](https://fontawesome.com/icons?d=gallery&q=folder&m=free) - same icon, but use the transparent version
* [project-diagram / site-map / code-branch](https://fontawesome.com/icons?d=gallery&c=code&m=free)
* [database / hdd / save](https://fontawesome.com/icons?d=gallery&c=computers&m=free)
* [basically anything under logistics or moving](https://fontawesome.com/icons?d=gallery&c=logistics,moving&m=free)

Sadly there is no whale tail icon included, but there appear to be plenty of options to choose from here depending on what analogy you want to use for a Tale.

**Comment by craig-willis** [comment]
In the end, I think a custom Tale icon would be best but a box or boxes seems best in the short term.
