### ISSUE TITLE
My Data displays all catalog data after navigating up

### ISSUE THREAD

**Issue by craig-willis** [whole-tale/dashboard#389]
A bug report and a change request.

To repeat:
* Start a tale instance
* Select Files > External Data > +  to open the Select Data modal
* Select My Data and browse into  a dataset
* Select "<-" to return to the My Data
* Note that the full catalog is displayed.

Also, I think we should reverse the order of WT Catalog/My Data -- MyData should be at the top and selected by default.

**Comment by ThomasThelen** [comment]
- Do the steps above
- Navigate to `WholeTale Catalog`
- Navigate back to `My Data`
- See the correct listing

(That may help when debugging)
