### ISSUE TITLE
Browse filter state mismatch when deleting a Tale

### ISSUE THREAD

**Issue by bodom0015** [whole-tale/dashboard#390]
### Steps to Reproduce
1. Compose a Tale
2. Navigate to "Browse" and filter to "Mine"
3. Delete a Tale

### Expected Results
Tale should be deleted, and one of two things should happen:
* Either the filter text should be reset to "All"
* Or the list should actually stay filtered to "Mine"

### Actual Results
* Tale is deleted
* List is refiltered to show all Tale
* Filter at the top (incorrectly) shows "Mine"

**Comment by ThomasThelen** [comment]
Similar (but not quite the same) as https://github.com/whole-tale/dashboard/issues/168. My guess is that the fix for this can be applied to 168 as well.
