### ISSUE TITLE
Confirm Tale Delete Modal Styling

### ISSUE THREAD

**Issue by ThomasThelen** [whole-tale/dashboard#394]
The modal (below) looks like it should have text in the center due to the way it's styled. We should either make it less wide, or use the same styling from the Tale View page

![screen shot 2019-02-15 at 9 48 02 am](https://user-images.githubusercontent.com/9289652/52874670-0b8f8d00-3107-11e9-8142-9e481e375fac.png)

In the Tale View page we show the following 

![screen shot 2019-02-15 at 10 06 08 am](https://user-images.githubusercontent.com/9289652/52875500-56aa9f80-3109-11e9-91ed-05e5a3de88ee.png)

**Comment by bodom0015** [comment]
Drilling down in the dev console, it appears that the text actually **is** there... it's text is just set to `color: #FFF!important;` in the CSS for some strange reason...

I can add a style tag to override this for now
