### ISSUE TITLE
[Firefox] Unable to Scroll Through WholeTale Catalog and My Data Modal

### ISSUE THREAD

**Issue by ThomasThelen** [whole-tale/dashboard#399]
This works fine on chrome, but when using Firefox I'm unable to scroll through the datasets. Note how there isn't a scrollbar in the Firefox screenshot, while there is one in the chrome.

The issue might be the size of the modal. It runs off the page in Firefox while it's clearly defined in chrome.

### Firefox
![screen shot 2019-02-15 at 10 43 12 am](https://user-images.githubusercontent.com/9289652/52877373-ab9ce480-310e-11e9-95a4-b9003723c3bb.png)

### Chrome

<img width="1672" alt="screen shot 2019-02-15 at 10 44 48 am" src="https://user-images.githubusercontent.com/9289652/52877406-bf484b00-310e-11e9-99f2-2f4d835f3042.png">

**Comment by bodom0015** [comment]
Seems to be the same behavior reported here: https://github.com/whole-tale/dashboard/pull/328#issuecomment-446699421

**Comment by ThomasThelen** [comment]
Oh wow I totally forgot about that, thanks for the reference

**Comment by bodom0015** [comment]
Seems like hard-coding a `style="max-height: 500px;"` here would work in the short term: https://github.com/whole-tale/dashboard/blob/master/app/components/ui/select-data-modal/template.hbs#L21

The only side-effect I see in Firefox from hard-coding this height is that the dimmer in the background behind the modal looks a bit short... a keen user might notice this and report it as a bug.

NOTE: this same style does **not** seem to affect Chrome, which correct uses the `height: -webkit-fill-available` style attribute
