### ISSUE TITLE
Compose function produces red error messages after submit

### ISSUE THREAD

**Issue by mbjones** [whole-tale/dashboard#40]
I composed and successfully created a Tale. After doing so, waiting a few seconds the screen changes state to show two red error boxes indicating that the frontend and data have not been selected.  Navigating back through the tabs produces differing behaviors, sometimes allowing the boxes to be cleared.

The red boxes persist even if I navigate away to another part of the app and then back to the Compose menu.

See screenshot below.

![screen shot 2017-05-24 at 12 15 03 pm](https://cloud.githubusercontent.com/assets/766407/26421776/1b8b5d74-407c-11e7-86ce-5073b74f6ad6.png)

**Comment by abrinckm** [comment]
Fixed after commit [6e940f](https://github.com/whole-tale/dashboard/commit/6e940ff7581fa9b5648d0b121edc298b2442f1e6).

The compose wizard wasn't properly resetting back to the "Tale Info" tab, so this made the red text confusing.
