### ISSUE TITLE
Run > Files > External Data: items listed with a leading slash

### ISSUE THREAD

**Issue by Xarthisius** [whole-tale/dashboard#411]
Files in the external data view have leading slashes:

![data](https://user-images.githubusercontent.com/352673/53031966-84f2ec80-3433-11e9-8f67-21be9fed7e3f.png)

### Expected result
No leading slashes

### How to reproduce
1. Deploy locally and register Ligo Tale
1. Run Ligo Tale
1. Navigate to Run > Files > External Data

**Comment by bodom0015** [comment]
I am not able to reproduce this locally - I think I have a fix for the issue, but am unable to test.

> 1. Deploy locally and register Ligo Tale

Is there a particular dataset I need to register to see this behavior? Or am I missing some way to import this Tale from `stage.wholetale.org` to my dev instance?

**Comment by Xarthisius** [comment]
Invalid test case.

**Comment by bodom0015** [comment]
Is this still an open issue? I don't think I have noticed this behavior anytime lately.
