### ISSUE TITLE
Illustration url doesn't save when changed via File > Metadata

### ISSUE THREAD

**Issue by craig-willis** [whole-tale/dashboard#435]
Problem:
* Changing the Illustration URL via the File > Metadata tab isn't persisted on save.

To repeat:
* Create/launch a Tale
* Go to File > Metadata
* Change the illustration URL and save
  * e.g., http://advances.sciencemag.org/content/advances/4/10/eaar4491/F2.large.jpg
* Go to Girder API, note that illustration hasn't changed
* Note that the same process works via old Tale view

Expected behavior:
* Illustration URL change is saved

**Comment by bodom0015** [comment]
Fixed by #444
