### ISSUE TITLE
Can't remove registered dataset

### ISSUE THREAD

**Issue by craig-willis** [whole-tale/dashboard#437]
Per https://github.com/whole-tale/wt-design-docs/issues/74#issuecomment-469799136

**Environment**:
* https://dashboard.stage.wholetale.org (v0.6rc3 )

**Problem**:
* After registering a dataset in Manage > Data, I can't remove it

**Test case:**
* Go to Manage > Data
* Register a dataset
* Try to remove it -- there is no Remove menu

**Expected**:
* Remove menu option present and when selected the dataset is removed from My Registered data.

**Comment by ThomasThelen** [comment]
I think this was fixed at some point. The Manage > Data page on the current stage environment appears to have the `remove` option on datasets.
Here's a dataset to test with: **https://search.dataone.org/view/doi:10.5063/F1PK0DF9**
![Screen Shot 2019-05-31 at 11 57 55 AM](https://user-images.githubusercontent.com/9289652/58728305-73f33900-839b-11e9-844a-8ebcdf9e11da.png)

**Comment by bodom0015** [comment]
Closing this, as `Remove` now appears for datasets listed under Manage > External Data
