### ISSUE TITLE
Multiple publishing problems

### ISSUE THREAD

**Issue by craig-willis** [whole-tale/dashboard#446]
Noting multiple problems found during review of https://github.com/whole-tale/dashboard/pull/344 that we will address after the initial PR is merged.

* Modal should not extend to the bottom of the page 
* Styling should be consistent with other modals (e.g., register)
* The "accordion" layout was part of the [original mockup](https://projects.invisionapp.com/freehand/document/nPpPcHSRg) but seems unnecessary and inconsistent with the rest of the site
* Modal should disable "Publish" button and change "Cancel" to "Close" on success.
* REST endpoint errors should be reported in the UI (e.g., 403 if publishing a Tale you don't own or 500) via ember.onerror
* Job errors should propagate via notification stream.
* We may consider re-adding the informative list of files to be published, but not as a selectable tree.

**Comment by bodom0015** [comment]
The job notifications are on my radar, but will likely require small backend changes to tweak what notifications to send and when to send them.
