### ISSUE TITLE
Tale title truncation in Run tab

### ISSUE THREAD

**Issue by craig-willis** [whole-tale/dashboard#449]
When recording the v0.7 demonstration, I noticed that we're applying the same truncation to the right and left panels of the Run tab for the Tale name/title.  Ideally, the Tale title the run page header would not be truncated or have a different limit?

**Comment by bodom0015** [comment]
I believe this has already been fixed: https://github.com/whole-tale/dashboard/blob/master/app/components/dashboard/run/left-panel/template.hbs#L9

**Comment by ThomasThelen** [comment]
In `Build: v0.7-0-gd90456f` the same number of characters are shown for the title and the card in `Launched Tales` (note that the same helper is used [here](https://github.com/whole-tale/dashboard/blob/a1f09ed123682dce2993ed505dd9c7baa9c5c5ae/app/components/ui/tale-instances/template.hbs#L43)). I like the idea of not truncating the title and letting it wrap before it hits the three-dot menu.

![Screen Shot 2019-06-12 at 12 37 19 PM](https://user-images.githubusercontent.com/9289652/59380870-ea365a80-8d0e-11e9-946e-a777701026ad.png)

**Comment by bodom0015** [comment]
This limit should already be a parameter to the `truncate-name` helper (or one of the other 2 similar helpers that we have available).

I'd be ok with wrapping the text, except that some of our layout relies on hard-coded heights in our .scss files... I expect that with making the height of `wt-paddleboard` variable, we would likely need to revisit these heights for the whole app.

**Comment by craig-willis** [comment]
With the new Run page design we have even more room now, right?  I don't have a problem with truncation, just wondering if we can use more of the available space.

**Comment by bodom0015** [comment]
Absolutely! If we stick with the existing helper(s), then what arbitrary number of characters should we display?

The other option might be to look into `white-space` / `word-wrap` / `text-overflow` CSS properties, which I believe can do some truncation based on the amount of space available. It is still unclear if these will play well with Semantic-UI / Ember / our existing styles / etc.
