### ISSUE TITLE
Add referenced dataset information to Tale metadata page

### ISSUE THREAD

**Issue by craig-willis** [whole-tale/dashboard#450]
Per the [mockups](http://www.crc.nd.edu/~kfurse/wholetale-css-mock-up-sui_f2018/run-meta-pre-run.html), we should be displaying dataset citation information on the metadata page for external datasets used in the Tale, particularly those with DOIs.

Ideally, we'd be able to display a formatted citation, as available via the [CrossRef citation formatting service](https://www.crossref.org/labs/citation-formatting-service).   But if this isn't possible (DataONE and Dataverse don't appear to support it), we should at least display links to the registered datasets, particularly via DOI.

**Comment by craig-willis** [comment]
It looks like this is possible via the [DataCite Content Resolver](https://support.datacite.org/docs/datacite-content-resolver) instead:

```
$ curl https://api.datacite.org/dois/text/x-bibliography/10.24431/rw1k118?style=apa
Cameron, M., London, J., Frost, K., Whiting, A., &amp; Boveng, P. (2017). <i>Satellite Telemetry Dataset (Raw): Juvenile Bearded and Spotted Seals, 2004-2006, Kotzebue, Alaska</i> [Data set]. Axiom Data Science. https://doi.org/10.24431/RW1K118
```

```
$ curl https://api.datacite.org/dois/text/x-bibliography/10.7910/dvn/ftfjtv?style=apa
Bisgaard, M. (2019). <i>Replication Data for: How Getting the Facts Right Can Fuel Partisan Motivated Reasoning</i> [Data set]. Harvard Dataverse. https://doi.org/10.7910/DVN/FTFJTV
```
Multiple styles are supported (see the [Cite](https://search.datacite.org/works/10.7910/dvn/ftfjtv) link on any dataset).  We could easily store citation metadata on each dataset in a generic format (bibtex, RIS) or call out to DataCite to render each time.  In the short term, I think a single display format should suffice.

**Comment by ThomasThelen** [comment]
This was completed in #456. User documentation can be found in the [0.7 docs PR](https://github.com/whole-tale/wt-design-docs/pull/81)
