### ISSUE TITLE
Add "Select Data" to "Create Tale" modal

### ISSUE THREAD

**Issue by craig-willis** [whole-tale/dashboard#453]
After completing #452, as per the mockups we will add the "Select Data" button to allow the user to select from registered datasets during Tale creation.

This includes:
* Adding the "Select Data" button to the modal
* Multiple selected datasets are displayed sensibly, possibly with a scrollbar.

As with #452, this needs to work with the "Analyze in WT" integration.

**Comment by Xarthisius** [comment]
I'd suggest the following changes to the mockup:
1. Convert `Input Data` to a list.
2. Move `Input Data` label to a header / attached label.
3. Add plus (add data) functionally to the header / attached label.
4. Present selected datasets as a list
5. Move hint text to the tooltip

Sample mockup of that part:

![list](https://user-images.githubusercontent.com/352673/55503669-c40c8400-5614-11e9-96d7-112d9c3200d6.png)

Showing the tooltip:

![with_tooltip](https://user-images.githubusercontent.com/352673/55503672-c7a00b00-5614-11e9-9c00-32473439482a.png)

**Comment by Xarthisius** [comment]
Alternatively to the tooltip, maybe a note at the top of the list?
![note](https://user-images.githubusercontent.com/352673/55504330-39c51f80-5616-11e9-8de2-556344af4c2e.png)

**Comment by abrinckm** [comment]
maybe investigate #457 while I'm in this component working. But not to fix until after this issue has been worked on and PR resolved of course.

**Comment by craig-willis** [comment]
Per [5/16 meeting](https://docs.google.com/document/d/1eC8_81IJlYGcvuuZLHDh6ePhide3BsQaudqk5hExIUo/edit), we will not implement select data on the create tale modal. We will support the parameters dataset ID (ala Analyze in WT) and link to documentation to describe how to add data after creating a tale.
