### ISSUE TITLE
Infinite number of GET /tale/{id} in Run view

### ISSUE THREAD

**Issue by Xarthisius** [whole-tale/dashboard#454]
It's a regression introduced by #344 . Specifically by: https://github.com/whole-tale/dashboard/blob/c7d10cd30944b25d2927a47ed44571d53e54d66e/app/components/dashboard/run/left-panel/component.js#L83-L93

inside `didRender()` method. That method is called very often (every time ember renders the view). It's also triggered when fetching underlying model. Putting `.findRecord('tale'` in there results in an infinite loop.

**Comment by ThomasThelen** [comment]
I removed this bit in the multiple-tale-authors branch (where the bug was originally found). Mike restricted publishing access in pull #451, so it should be fine to remove. 

Would you prefer that I pull this out in a different PR?

**Comment by Xarthisius** [comment]
> I removed this bit in the multiple-tale-authors branch (where the bug was originally found). Mike restricted publishing access in pull #451, so it should be fine to remove.
> 
> Would you prefer that I pull this out in a different PR?

I cherry-picked your commit and issued #455

**Comment by Xarthisius** [comment]
Fixed by #445
