### ISSUE TITLE
Reverse order of Tales and registered data

### ISSUE THREAD

**Issue by ian-taylor** [whole-tale/dashboard#46]
We should reverse the order of tales and registered datasets to that the most recent appears first.

**Comment by Xarthisius** [comment]
Every GET /model endpoint in girder accepts following query params: 

 * `sort` - Field to sort the result set by. (string)
 * `sortdir` -  Sort order: 1 for ascending, -1 for descending. (int)

**Comment by abrinckm** [comment]
Completed in commit [33e9eb1](https://github.com/whole-tale/dashboard/commit/33e9eb150ca23d90393e88cb53da726d83e696ff)
