### ISSUE TITLE
Tale name isn't refreshed after updating in metadata editor

### ISSUE THREAD

**Issue by ThomasThelen** [whole-tale/dashboard#463]
After saving a Tale with a new title, the backend is properly updated however, the UI still shows the previous name.

Steps to Reproduce:
1. Launch a Tale that you own
2. Navigate to run>metadata
3. Change the name of the Tale
4. Save
5. Note that the UI shows the old name
6. Request the tale via girder API
7. See that the tale.title is correct

**Comment by Xarthisius** [comment]
It's happening because Run view currently shows instance (and its name) instead of the Tale object that you're modifying. However, I believe it's going to be fixed by https://github.com/whole-tale/dashboard/pull/459

**Comment by bodom0015** [comment]
That is correct, it #459 will change the view from using `model.name` (previously an `Instance` model) to `model.title` (now a `Tale` model).

See https://github.com/whole-tale/dashboard/pull/459/files#diff-51cf2528add713a8ed071d3b0b504de0R11

**Comment by bodom0015** [comment]
This should now be fixed.
