### ISSUE TITLE
Fix left menu

### ISSUE THREAD

**Issue by MatthewTurk** [whole-tale/dashboard#47]
Left menu should be "fixed & hideable", not "hidden & fixable".  Logout should be upper left, near username.  By default menu needs to be open.  Discussion among the exec team was that it's not clear it even needs to be hidden as opposed to simply out as a navbar.

**Comment by MatthewTurk** [comment]
Right now, if you click "Floating Menu" and then uncollapse it, the layout changes.

Having the menu just *always* be expanded would fix this.  The name "Floating Menu" is a bit unclear as well, as it looks like a destination, whereas usually the `<<` box is used to indicate collapsing.

**Comment by ian-taylor** [comment]
Of course removing functionality would fix issues with the functionality :) but its unclear what you want here. Shall we try a collapse << and align the look ?

**Comment by MatthewTurk** [comment]
My preference would be the remove it completely.  But, adding the `[<<]` and `[>>]` would be an improvement.

**Comment by ian-taylor** [comment]
Personally, I think we should try and make it work. Other systems like gdrive, dropbox, etc that have file management interfaces use the full browser width and have hamburger menus to go to other functionality. We added the fixed menu but It doesn't seem prudent to remove the hamburger option as well.  And although some may prefer a fixed menu all of the time, there will be others that will not. I also think that the more room we leave horizontally the better or things will look cluttered, especially now we're moving towards a more tile styled click through interface where menus are needed less frequently e.g. all tales, images etc click through to functionality that relate to them.   I'll look to see how this is done elsewhere or improvise with the << >> approach. If anyone can think of any examples elsewhere, please paste them here for reference.

**Comment by nigaffney** [comment]
I fear it is one of those "I was on the site and suddenly the menu went away and I cant find it" issues we will have to help with time and time again. Until we get to a point where there is no way to reduce clutter of the page beyond hiding this menu, I really think we should get rid of it as a feature.  Ochams razor of interface design (Or Steve Jobs if you want...).  Until we have a userbase to start testing advanced  UI interfaces with, I think keep it simple.

**Comment by ian-taylor** [comment]
I agree except that Steve Jobs would definitely cut the fixed menu on the grounds it took too much space and keep it simple and figure out how to make it obvious to click the hamburger or other icon to drop down the menu...

**Comment by ian-taylor** [comment]
I think the best people to decide this are our users after we have some feedback... but if you all really want to have a fixed menu only, and remove the dropdown one, then I will fall on my sword.

**Comment by MatthewTurk** [comment]
Sounds good, @ian-taylor , thanks!

**Comment by abrinckm** [comment]
Disabled it but did not remove it [094d385](https://github.com/whole-tale/dashboard/commit/094d385eacece3295a7afdc9c883d340138702a1)

**Comment by craig-willis** [comment]
No longer applicable to new ui
