### ISSUE TITLE
Un-saved Tale Authors Not Preserved on Page Navigation

### ISSUE THREAD

**Issue by ThomasThelen** [whole-tale/dashboard#470]
When changes are made on the metadata page but not saved, they are preserved as the user navigates around the site. The Tale authors are getting refreshed when the user navigates to the metadata page, which wipes out un-saved changes

**Comment by bodom0015** [comment]
Same cause as #292, with a slightly different effect due to the level of indirection around `tale.authors`

**Comment by ThomasThelen** [comment]
This is a non issue, see [this PR](https://github.com/whole-tale/wt-design-docs/pull/82)
