### ISSUE TITLE
"Analyze in Whole Tale" not Redirecting on Successful Compose

### ISSUE THREAD

**Issue by ThomasThelen** [whole-tale/dashboard#471]
After visiting `https://girder.stage.wholetale.org/api/v1/integration/dataverse?fileId=3323458&siteUrl=https%3A%2F%2Fdataverse.harvard.edu` and composing the Tale, I'm not redirected to the Run page.

To Reproduce:
1. Navigate to ` https://girder.stage.wholetale.org/api/v1/integration/dataverse?fileId=3323458&siteUrl=https%3A%2F%2Fdataverse.harvard.edu`
2. Select an environment
3. Create the Tale
4. Note that the compose page is refreshed when finished

**Comment by ThomasThelen** [comment]
When trying to reproduce this, I get in an infinite loop in the [import task](https://github.com/whole-tale/gwvolman/blob/master/gwvolman/tasks.py#L553).
It looks like Stage gets past this part.

**Comment by bodom0015** [comment]
I have seen this before stack trace before, but I forget how to get rid of it... I know @Xarthisius and @craig-willis have helped debug this at least once, but I forget what the resolution was.

It still happens occasionally on my dev instance, but it's been a couple of months since I've seen it:
```
[2019-03-13 19:21:59,817: INFO/ForkPoolWorker-1] Calling: girderfs -c wt_home --api-url http://10.0.0.2:8080/api/v1 --api-key dXMAGM5OCzn4bTH0yXEbuzgJcQzWPgsLfnPWYuaP /var/lib/docker/volumes/5c816e76956ee60001be32b2_lambert8_e7XRxt/_data/home 5c7d7140956ee600012e6f5e
open: Permission denied
mount.davfs: can't mount using fuse kernel file system
mount.davfs: trying coda kernel file system
mount.davfs: no free coda device to mount
Traceback (most recent call last):
  File "/usr/local/bin/girderfs", line 11, in <module>
    load_entry_point('girderfs==0.6.0rc3', 'console_scripts', 'girderfs')()
  File "/usr/local/lib/python3.5/dist-packages/girderfs/__main__.py", line 92, in main
    subprocess.check_output(cmd, shell=True)  # FIXME
  File "/usr/lib/python3.5/subprocess.py", line 626, in check_output
    **kwargs).stdout
  File "/usr/lib/python3.5/subprocess.py", line 708, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command 'echo "lambert8
token:Wdl5OvjyhFg7NSQMRuUYCDkHm17GgjeMZJid50z1D6wFp0o4g4PpKbo6rUob3iNC" | mount.davfs -o uid=1000,gid=100 http://10.0.0.2:8080/homes/lambert8 /var/lib/docker/volumes/5c816e76956ee60001be32b2_lambert8_e7XRxt/_data/home' returned non-zero exit status 1
```

@craig-willis , @Xarthisius? Any recollection on what was happening here?
I wonder if a `make clean` / `make dev` on deploy-dev would fix it?

**Comment by Xarthisius** [comment]
Can you verify that `fuse` and `davfs2` are installed on host system and that `fuse` kernel module is loaded?

**Comment by bodom0015** [comment]
Both packages appear to be installed:
```
root@lambert8-dev:/home/ubuntu# dpkg -l | grep davfs
ii  davfs2                           1.5.2-1.2                                  amd64        mount a WebDAV resource as a regular file system
root@lambert8-dev:/home/ubuntu# dpkg -l | grep fuse
ii  fuse                             2.9.4-1ubuntu3.1                           amd64        Filesystem in Userspace
ii  libfuse2:amd64                   2.9.4-1ubuntu3.1                           amd64        Filesystem in Userspace (library)
```

`modprobe -a fuse` doesn't return an error on my VM - does this mean the module is correctly loaded? Linux Kernel modules are not something I have had very much experience with, and what little experience I have is over 10 years old..

**Comment by ThomasThelen** [comment]
It looks like I don't have fuse installed, but the rest looks close to @bodom0015 's 

```
thomas@thomas-girder:~/deploy-dev$ dpkg -l | grep davfs
thomas@thomas-girder:~/deploy-dev$ dpkg -l | grep fuse
ii  fuse                                  2.9.7-1ubuntu1                     amd64        Filesystem in Userspace
ii  libfuse2:amd64                        2.9.7-1ubuntu1                     amd64        Filesystem in Userspace (library)
thomas@thomas-girder:~/deploy-dev$ modprobe -a fuse
thomas@thomas-girder:~/deploy-dev$
```

**Comment by craig-willis** [comment]
Just to circle back on the davfs issues.  I'm reasonably certain now that the root cause for my original problems was running on Ubuntu.  After switching to CoreOS I never saw them again.  So, setting `privileged=true` on the deploy-dev `run-worker.sh` script is likely also what I did many months ago. So we either need to figure out the right caps or deploy on CoreOS.

**Comment by ThomasThelen** [comment]
I think it makes sense to switch over to CoreOS since that's what we're deploying on. After 0.7, I'll migrate over.
