### ISSUE TITLE
'Public' flag on public Tale defaults to false

### ISSUE THREAD

**Issue by ThomasThelen** [whole-tale/dashboard#499]
After making a Tale public and re-visiting the metadata page, the `Public` switch is defaulted to false.

### To Reproduce:

1. Launch a Tale that you own
1. Navigate to the Run > Metadata page
1. Add an author and make it public
1. Save
1. Navigate to Browse, and then back to the metadata page
1. Note that the Public flag is set to false

![demo](https://user-images.githubusercontent.com/9289652/59683481-1e859d00-918d-11e9-98a2-ce7b24277857.gif)

**Comment by bodom0015** [comment]
This no longer appears to be an issue.. dashboard.stage is still using an older version of the dashboard, but dashboard.dev has the newly-refactored stuff.

Seems to be working as expected on dashboard.dev

**Comment by ThomasThelen** [comment]
Just re-tested and can confirm this seems to no longer be an issue
