### ISSUE TITLE
Compose query parameters do not clear when navigating

### ISSUE THREAD

**Issue by craig-willis** [whole-tale/dashboard#500]
To repeat:
* https://dashboard.local.wholetale.org/compose?asTale=True&name=Dataverse%20IRC%20Metrics&uri=https%3A%2F%2Fdev2.dataverse.org%2Fdataset.xhtml%3FpersistentId%3Ddoi%3A10.5072%2FFK2%2FNYNHAM
* Select Browse then Compose
 
What happens:
* The query parameters are retained and there's no way to clear them without modifying the UR

What's expected:
* Navigating to Browse or Run should clear the compose query parameters, or at least some other intuitive way to clear the compose page (reset?)

**Comment by bodom0015** [comment]
This is no longer an issue, since #465 has been merged
