### ISSUE TITLE
User settings

### ISSUE THREAD

**Issue by craig-willis** [whole-tale/dashboard#504]
[Needs UI/UX input]

For integration with Dataverse, Zenodo, and Agave, we'll need a way to collect additional information from users to connect to associate accounts.  For example, Dataverse requires that users provide an API key. Zenodo and Agave may be implemented via Oauth. We could also use this for DataONE/ORCID integration.

See draft design document:
https://docs.google.com/document/d/10O3r0tZ7Q86uZLpmnhUaaMRIsM1c-gGYYzSc7bf9wO8/

**Comment by bodom0015** [comment]
Closing, as this is now being tracked under multiple issues:
#559 
#560 
#561 
etc
