### ISSUE TITLE
Google analytics code

### ISSUE THREAD

**Issue by matthewturk** [whole-tale/dashboard#52]
Google analytics for the dashboard should be reporting back to the main WT google analytics account on wholetale.org.  This should be set up at build time though, and be optional, for the case of other deployments.

**Comment by abrinckm** [comment]
Do we have a main WT google analytics account?

**Comment by MatthewTurk** [comment]
We don't -- and since I made this issue I found out that we need a privacy policy in place before we open one.

**Comment by Xarthisius** [comment]
We can revisit once we have said policy in place.
