### ISSUE TITLE
Dashboard displays Job as Tale during import

### ISSUE THREAD

**Issue by craig-willis** [whole-tale/dashboard#523]
When testing https://github.com/whole-tale/gwvolman/pull/82 I noticed a strange behavior -- a 400 error in the console (invalid tale ID) and a Tale displayed on the Browse page with title "Import Tale".  It appears that during the import flow the compose dialog is treating a Job response as a Tale.

To repeat:
* Assumes deploy-dev with Ligo tale and `["https://dev2.dataverse.org"]` in `extra_hosts` in [wholetale plugin settings](https://girder.local.wholetale.org/#plugins/wholetale/config)
* Checkout and build dashboard `master` branch
* Open dev console
* Go to https://dashboard.local.wholetale.org/browse?uri=https%3A%2F%2Fdev2.dataverse.org%2Fdataset.xhtml%3FpersistentId%3Ddoi%3A10.5072%2FFK2%2FNYNHAM&name=Dataverse+IRC+Metrics
* While Tale is starting, select "View" on Ligo tale then "Back to Dashboard"
* Note that a Tale is displayed with title "Import Tale" and there is a 400 error with invalid tale ID message.

<img width="1660" alt="Screen Shot 2019-07-31 at 11 13 55 AM" src="https://user-images.githubusercontent.com/4334350/62224670-0bb5d900-b385-11e9-82ba-4be13a83ce1d.png">

**Comment by craig-willis** [comment]
Also noting that when testing this same flow with https://github.com/whole-tale/dashboard/pull/517, I am redirected to the "Job" tale (which doesn't exist).

**Comment by Xarthisius** [comment]
I believe this was fixed by https://github.com/whole-tale/girder_wholetale/pull/347 Please reopen if it's still the case.
