### ISSUE TITLE
First registered dataset doesn't appear until after refresh

### ISSUE THREAD

**Issue by craig-willis** [whole-tale/dashboard#532]
Found this while testing v0.8rc1 in Chrome.

Pre-conditions:
* No external data in your Manage > Data

To repeat:
* Register doi:10.5065/D6862DM8
* Note that the dataset doesn't appear in the list
* Refresh, it should be there
* Register doi:10.7910/DVN/SZ9YXZ
* Note that the dataset appears in the list

Expected:
* First dataset appears in list without refresh

**Comment by bodom0015** [comment]
I can't seem to reproduce this one reliably... Remember that registering a dataset is asynchronous, so there may be a slight delay (usually only a couple of seconds) after confirming the "Register" modal before the dataset actually appears in the UI.

My experience was as follows: http://recordit.co/EFNXetUfAq

**Comment by Xarthisius** [comment]
Can't reproduce either.
