### ISSUE TITLE
Incorrect Instance State on Browse Page

### ISSUE THREAD

**Issue by ThomasThelen** [whole-tale/dashboard#549]
Possibly related to (but not caused by) Pull #534

The idea of inconsistent state came up in Kacper's [girder_wholetale PR](https://github.com/whole-tale/girder_wholetale/pull/351), see the comments.

While testing, I found an easier way to reproduce the incorrect state.

### Steps
1. Navigate to the browse page (stage environment is fine)
2. Launch a Tale
3. Quickly navigate back to the browse page (before the Tale is completed)
4. Note the spinner on the Tale
5. Wait for the Tale to finish launching
6. Open a new tab and navigate to the browse page
7. Note the `Stop` button
8. Navigate back to your first tab
9. Note that the spinner is present

**Comment by craig-willis** [comment]
I ran into this while testing https://github.com/whole-tale/dashboard/pull/550. For me, it doesn't matter if I navigate back before or after the tale starts on the run page:

My steps:
1. Navigate to the browse page 
1. Launch a Tale
1. a) Wait for it to start b) don't wait for it to start
1. Go "Back to Dashboard"
1. Note the spinner on the Tale
1. Wait for the Tale to finish launching
1. Note that the spinner is present

Hit refresh and all is good.
