### ISSUE TITLE
Discussion to nail down Run > Files modal requirements

### ISSUE THREAD

**Issue by bodom0015** [whole-tale/dashboard#553]
Since we haven't formally documented this relatively new feature / use case anywhere (that I know of), there has been much confusion surrounding these 2 modals.

My current understanding is as follows:

**Select Data modal**
- Top level offers the user a list of Datasets
- User should be allowed to navigate into a Dataset to shows the Folders and Items within
- Selecting a Dataset, Folder, or Item will add it to the user's "Selection"
- Upon submitting the modal, "Selection" is parsed into `tale.dataSet`, then a `PUT /tale/:id` is performed to save to the backend

**Tale Workspaces modal**
- Top level offers the user a list of Tales
    - NOTE: current Tale should be omitted/hidden
- User should be allowed to navigate into a Tale to show the workspace Folders and Items within
- Selecting a Folder or Item will add it to the user's "Selection"
    - NOTE: entire Workspaces cannot be selected (otherwise "Move to Workspace" should be prevented, as it would break the workspace folder structure for other Tales)
- After selection, user should be offered an option to `Move to Workspace` or `Copy to Workspace` 
    - `Move to Workspace` will move the selected Folders and Items to the current Tale's Workspace
    - `Copy to Workspace` will copy the selected entities in place, then move the copied entities to the current Tale's Workspace

Does the above description sound correct, or have I left anything out?

**Comment by Xarthisius** [comment]
I think that description is correct and complete.
