### ISSUE TITLE
User menu option doesn't display on resize

### ISSUE THREAD

**Issue by craig-willis** [whole-tale/dashboard#584]
Problem:
* If I resize browser window to the point that the  "hamburger" menu displays, the User menu isn't available. 

<img width="956" alt="Screen Shot 2020-01-22 at 12 38 11 PM" src="https://user-images.githubusercontent.com/4334350/72918750-366d6280-3d14-11ea-9408-9379619fe0b2.png">

**Comment by bodom0015** [comment]
Ahhh, I've never noticed that and didn't know it was a thing!

There are a couple of different `header.hbs` files that make up / have made up the navbar, so it is unclear what in there is actually still being used.

I can try to find which source this menu corresponds to and add in the missing Settings nav.
