### ISSUE TITLE
Prevent users from clicking 'Create tale and launch` multiple times

### ISSUE THREAD

**Issue by ThomasThelen** [whole-tale/dashboard#587]
From Mike H [here](https://github.com/whole-tale/wt-design-docs/issues/99)

Steps to reproduce:

1. Browse > Create New... > Create New Tale
2. Enter details
3. Click on "Create tale and launch"

There is no feedback to the user that the button was clicked until the server processes the relevant request. The user can click repeatedly on the "Create tale and launch" button, each click triggering a new request, which creates a new tale. Presumably when the server acknowledges the first request, the modal disappears, but multiple tales are created.

**Comment by bodom0015** [comment]
Fixed by #594
