### ISSUE TITLE
Connect account dialog displays other accounts keys

### ISSUE THREAD

**Issue by craig-willis** [whole-tale/dashboard#618]
When testing https://github.com/whole-tale/girder_wholetale/pull/407, I noticed this: 

<img width="936" alt="Screen Shot 2020-03-06 at 11 48 44 AM" src="https://user-images.githubusercontent.com/4334350/76104392-44640380-5fa1-11ea-8c6e-5e8717231e9d.png">

I had connected Zenodo then went to connect Dataverse, and see cached target and token information.  I had no Dataverse tokens configured, so this should be empty and certainly not showing sandbox.zenodo.org.

**Comment by Xarthisius** [comment]
That's caused by that PR. Fixing...

**Comment by craig-willis** [comment]
Ah, didn't occur to me that your PR caused it. The fix appears to work.
