### ISSUE TITLE
Odd highlighting

### ISSUE THREAD

**Issue by MatthewTurk** [whole-tale/dashboard#65]
When I move my mouse around on the main page, the "View" boxes (and the associated shadow) highlight and unhighlight in ways that don't completely correspond to my pointer's position.  It almost seems like I might be moving my mouse faster than the shadowing effect happens, and so it's queuing up events.  This means that it can be hard to click on the "View" button at all.

If necessary, switching to a zero-delay highlight would be fine to fix it.

I'm on chrome on linux.

**Comment by abrinckm** [comment]
I've reduced the delay in the highlighting in commit [020560b](https://github.com/whole-tale/dashboard/commit/020560ba40b42691b64b6b7bc5b1054b16ec670e). 
However, I didn't experience any problems with clicking the view button. The button was immediately clickable even during animation and before the animation finished. So I'm not quite sure what is causing that problem for you, but hopefully this commit will fix it.

**Comment by abrinckm** [comment]
Let me know if this fixed the issue for you :)

**Comment by ian-taylor** [comment]
@MatthewTurk what linux chrome version is this happening on ? does it happen on other linux browsers also?

Its ok on chrome on the mac. I'll try an repeat it on my ubuntu VM

**Comment by ThomasThelen** [comment]
I think Adam's code change in 020560b fixed this-I'm unable to reproduce this on chrome and firefox.

**Comment by MatthewTurk** [comment]
SGTM!  I am not seeing the behavior anymore.
