### ISSUE TITLE
Minor corner issue on the header

### ISSUE THREAD

**Issue by MatthewTurk** [whole-tale/dashboard#67]
The corner on the lower left of the header is rounded, which puts a bit of an odd visual break.  I think this corner (not the others) should be square.

![corner](https://user-images.githubusercontent.com/89019/29329128-704280b6-81ba-11e7-8c49-73ae1b2828e4.png)

**Comment by abrinckm** [comment]
Completed in [9ec2849](https://github.com/whole-tale/dashboard/commit/9ec28497ba3f385d578e418223f86c497fc80658)
