### ISSUE TITLE
DOI Resolution User Expectations

### ISSUE THREAD

**Issue by ekansa** [whole-tale/dashboard#69]
In adding data, there's a search interface that has some user experience troubles.

It would be great to set some user expectations in the interface with regard to DOI resolution. I tried entering in DOIs to different datasets in different repositories, and these did not appear as search results. 

Ideally, repository owners should do some content negotiation, but for the time being, some warning to users that only certain DataONE repository DOIs will work.

**Comment by ekansa** [comment]
Sorry! Posted this issue in the wrong repo

**Comment by Xarthisius** [comment]
@ekansa don't worry about that! Having your feedback is a few order of magnitude more important than getting it in a specific repo.
