### ISSUE TITLE
Reloading or opening in a new tab gives 404

### ISSUE THREAD

**Issue by MatthewTurk** [whole-tale/dashboard#71]
If I ctrl-click on something on dashboard.wholetale.org or if I press enter in the URL entry bar, it gives me a 404.

To replicate, go to dashboard.wholetale.org and hold Ctrl down and click on "My Data".

**Comment by ian-taylor** [comment]
This seems to be a server config issue - dashboard dev works ok @Xarthisius ?

**Comment by Xarthisius** [comment]
I copied nginx's config from dev to prod. Let me know if that fixes the issue

**Comment by MatthewTurk** [comment]
Sadly, no.
