### ISSUE TITLE
Steps UI for creating Recipe and Image (Step 2)

### ISSUE THREAD

**Issue by abrinckm** [whole-tale/dashboard#82]
Acceptance criteria:

**Comment by AMarczak** [comment]
Acceptance criteria:

**Comment by abrinckm** [comment]
Resolved after commits [04f79d4](https://github.com/whole-tale/dashboard/commit/04f79d45df6cd219a57eb3f0fe46f5f8dc9474b0) and [d6b84d8](https://github.com/whole-tale/dashboard/commit/d6b84d8a73dc23d10addbb3e7334c47b78c94eb8)
