### ISSUE TITLE
Removing Tale object doesn't wait for backend response

### ISSUE THREAD

**Issue by Xarthisius** [whole-tale/dashboard#92]
It's possible to click on remove button either in the tale view or "tale-flix" on every Tale. It immediately removes object for the current dashboard state, even if backend properly responds with 403.

**Comment by swyngaard** [comment]
Fixed with commit [a79f1f0](https://github.com/whole-tale/dashboard/commit/a79f1f08b8002f7fdfec81f01bd6d0d0b194c137)

**Comment by Xarthisius** [comment]
@swyngaard could you backport it to the stable branch?

**Comment by abrinckm** [comment]
Testing something
