### ISSUE TITLE
Advanced Search General Search Not Matching All Filters

### ISSUE THREAD

**Issue by ian-taylor** [whole-tale/dashboard#97]
I added the project title to the advanced search using the filters and did the following:

- searched "ADC" using project.title -> found projects ok
- searched "ADC" using the google style general box -> did not find projects

Shouldn't this have worked the same?

**Comment by abrinckm** [comment]
The project.title wasn't included as a filter for the google style general box. I believe it needs to be though so I will add it.

**Comment by abrinckm** [comment]
Resolved in [6bd4e6](https://github.com/crcresearch/ember-craft-repository/commit/6bd4e6d7db58a98ad5ce67fe1d33d3ccee34fff6)
