### ISSUE TITLE
Add tale filtering to the tales-widget

### ISSUE THREAD

**Issue by abrinckm** [whole-tale/dashboard#99]

**Comment by abrinckm** [comment]
Resolved in commit [e942be3](https://github.com/whole-tale/dashboard/commit/e942be31fadd282ca4f066076c3a0436147cf452)

**Comment by ian-taylor** [comment]
Same issues as home page here - there's an issue with the filter that affects the in page search.  If you do not select a filter when the page first loads, then the search does not work. It returns nothing and then does not allow you to remove the search. Once you select a filter, all works ok.

Fix would be to have the default to filter to All.

**Comment by cyberdante** [comment]
I believe this to be solved as well.
